import { Stock } from "./stock-data";

export const etfUniverse: Stock[] = [
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    sector: "Broad Market",
    type: "etf" as const,
    price: 562.75,
    change: 4.23,
    changePercent: 0.76,
    marketCap: "$550B",
    peRatio: 25.8,
    dividendYield: 1.24,
    fiftyTwoHigh: 613.23,
    fiftyTwoLow: 480.57,
    analystRating: "Buy",
    aiScore: 84,
    beta: 1.0,
    description: "The original S&P 500 index ETF tracking 500 large-cap US equities by market cap weight",
    thesis:
      "Owning the 500 largest US companies in a single liquid vehicle. Decades of data show most active managers underperform SPY after fees. Core holding for any long-term equity portfolio.",
    risks: [
      "Top-heavy concentration in mega-cap tech (Apple, Nvidia, Microsoft make up 20%+)",
      "Full US market drawdowns with no downside buffer",
      "Currency and rate cycle sensitivity",
    ],
    catalysts: [
      "Continued earnings growth from mega-cap constituents",
      "Federal Reserve rate cuts expanding equity multiples",
      "Corporate buyback programs supporting index price",
    ],
    expenseRatio: 0.0945,
    aum: "$550B",
    holdings: 503,
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
    sector: "Technology",
    type: "etf" as const,
    price: 484.60,
    change: 5.12,
    changePercent: 1.07,
    marketCap: "$320B",
    peRatio: 31.4,
    dividendYield: 0.58,
    fiftyTwoHigh: 540.81,
    fiftyTwoLow: 400.44,
    analystRating: "Buy",
    aiScore: 86,
    beta: 1.19,
    description: "Tracks the Nasdaq-100 index, heavily weighted toward large-cap technology and growth companies",
    thesis:
      "Concentrated exposure to the highest-growth segment of the US equity market. AI, cloud, and semiconductor tailwinds benefit top holdings directly. Outperformed SPY over every 10-year rolling window since inception.",
    risks: [
      "High valuation multiples vulnerable to rate shock",
      "Mega-cap tech regulatory and antitrust risk",
      "No financial or energy sector exposure limits diversification",
    ],
    catalysts: [
      "AI-driven revenue acceleration at Microsoft, Nvidia, and Meta",
      "Continued margin expansion across software constituents",
      "Rate cuts disproportionately benefit long-duration growth names",
    ],
    expenseRatio: 0.2,
    aum: "$320B",
    holdings: 101,
  },
  {
    ticker: "VTI",
    name: "Vanguard Total Stock Market ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 278.34,
    change: 1.89,
    changePercent: 0.68,
    marketCap: "$450B",
    peRatio: 24.9,
    dividendYield: 1.31,
    fiftyTwoHigh: 303.65,
    fiftyTwoLow: 236.67,
    analystRating: "Buy",
    aiScore: 83,
    beta: 1.0,
    description: "Owns the entire US equity market across large, mid, and small caps in one fund",
    thesis:
      "Broader diversification than SPY by including mid and small caps. Vanguard's at-cost structure (0.03% expense ratio) means more of every dollar stays invested. True total market exposure in a single trade.",
    risks: [
      "Small and mid cap exposure adds volatility versus pure large-cap funds",
      "Correlated with entire US economy -- no defensive tilt",
      "Less liquid than SPY during stress events",
    ],
    catalysts: [
      "Small and mid cap valuation catch-up if rates decline",
      "Broad earnings recovery across all market cap bands",
      "Continued inflows from 401(k) default fund adoptions",
    ],
    expenseRatio: 0.03,
    aum: "$450B",
    holdings: 3680,
  },
  {
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 221.45,
    change: -0.87,
    changePercent: -0.39,
    marketCap: "$78B",
    peRatio: 27.6,
    dividendYield: 1.11,
    fiftyTwoHigh: 244.47,
    fiftyTwoLow: 185.33,
    analystRating: "Hold",
    aiScore: 74,
    beta: 1.22,
    description: "Tracks 2000 small-cap US stocks in the Russell 2000 index",
    thesis:
      "Small caps historically outperform large caps over 10+ year periods. Domestically focused businesses benefit most from lower interest rates and a strong US economy. Attractive valuations relative to large caps.",
    risks: [
      "Higher sensitivity to credit conditions -- many holdings carry floating rate debt",
      "Earnings quality lower than large caps with more unprofitable companies",
      "Underperformed large caps for over a decade creating momentum headwinds",
    ],
    catalysts: [
      "Fed rate cuts reducing borrowing costs for leveraged small-cap companies",
      "Domestic economic acceleration benefiting locally focused businesses",
      "Rotation from mega-cap concentration into small cap value",
    ],
    expenseRatio: 0.19,
    aum: "$78B",
    holdings: 1971,
  },
  {
    ticker: "VOO",
    name: "Vanguard S&P 500 ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 516.60,
    change: 3.88,
    changePercent: 0.76,
    marketCap: "$570B",
    peRatio: 25.8,
    dividendYield: 1.27,
    fiftyTwoHigh: 563.03,
    fiftyTwoLow: 441.35,
    analystRating: "Buy",
    aiScore: 85,
    beta: 1.0,
    description: "Vanguard's S&P 500 fund offering the same index exposure as SPY at a fraction of the cost",
    thesis:
      "Functionally identical to SPY but with an 0.03% expense ratio versus 0.0945% for SPY. Long-term cost compounding makes VOO materially superior for buy-and-hold investors. Vanguard's ownership structure aligns incentives with shareholders.",
    risks: [
      "Same concentration risk as SPY in mega-cap technology",
      "Full participation in market drawdowns without any buffer",
      "Less intraday liquidity than SPY for large institutional trades",
    ],
    catalysts: [
      "S&P 500 earnings growth driven by AI infrastructure buildout",
      "Passive fund inflows creating structural buying pressure",
      "Buyback activity from cash-rich index members",
    ],
    expenseRatio: 0.03,
    aum: "$570B",
    holdings: 503,
  },
  {
    ticker: "VUG",
    name: "Vanguard Growth ETF",
    sector: "Technology",
    type: "etf" as const,
    price: 373.82,
    change: 3.94,
    changePercent: 1.07,
    marketCap: "$155B",
    peRatio: 34.2,
    dividendYield: 0.49,
    fiftyTwoHigh: 416.00,
    fiftyTwoLow: 305.56,
    analystRating: "Buy",
    aiScore: 82,
    beta: 1.14,
    description: "Tracks US large-cap growth stocks screened for earnings and revenue growth characteristics",
    thesis:
      "Pure-play on US growth at Vanguard's rock-bottom 0.04% expense ratio. Top holdings are the same AI-era compounders that have driven a decade of equity returns. Superior long-run returns to value in low-inflation environments.",
    risks: [
      "High duration risk -- growth stocks hurt most when rates rise",
      "Concentrated in technology at 55%+ of portfolio weight",
      "Valuation premium to the broad market requires continued earnings delivery",
    ],
    catalysts: [
      "AI monetization accelerating earnings per share at top holdings",
      "Multiple expansion if long-term rates normalize lower",
      "Continued innovation cycles extending competitive moats",
    ],
    expenseRatio: 0.04,
    aum: "$155B",
    holdings: 183,
  },
  {
    ticker: "VTV",
    name: "Vanguard Value ETF",
    sector: "Finance",
    type: "etf" as const,
    price: 168.42,
    change: 0.54,
    changePercent: 0.32,
    marketCap: "$125B",
    peRatio: 18.1,
    dividendYield: 2.37,
    fiftyTwoHigh: 178.97,
    fiftyTwoLow: 144.28,
    analystRating: "Buy",
    aiScore: 76,
    beta: 0.88,
    description: "Tracks US large-cap value stocks with low price-to-book and price-to-earnings ratios",
    thesis:
      "Value stocks trade at a historically wide discount to growth. Rising rates favor financials and energy, VTV's top sectors. Dividend income provides a return floor in flat or down markets.",
    risks: [
      "Value factor has underperformed growth for over a decade",
      "Heavy financials exposure creates rate and credit cycle sensitivity",
      "Slow earnings growth relative to technology sector",
    ],
    catalysts: [
      "Mean reversion from extreme growth-to-value valuation spread",
      "Financials benefiting from steeper yield curve",
      "Institutional rotation to defensive dividend payers in late cycle",
    ],
    expenseRatio: 0.04,
    aum: "$125B",
    holdings: 344,
  },
  {
    ticker: "SCHD",
    name: "Schwab US Dividend Equity ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 27.85,
    change: 0.12,
    changePercent: 0.43,
    marketCap: "$65B",
    peRatio: 17.4,
    dividendYield: 3.54,
    fiftyTwoHigh: 29.67,
    fiftyTwoLow: 23.49,
    analystRating: "Strong Buy",
    aiScore: 80,
    beta: 0.78,
    description: "Selects 100 US stocks with high dividend yield, strong fundamentals, and 10-year dividend growth history",
    thesis:
      "Best-in-class dividend ETF with a rigorous quality screen that filters for both yield and dividend sustainability. 0.06% expense ratio at Schwab. Consistent dividend growth creates an inflation-fighting income stream.",
    risks: [
      "Rising rates make dividend yields less attractive relative to fixed income",
      "Sector tilts away from high-growth technology reduces upside capture",
      "Dividend cuts during recessions can reduce income unexpectedly",
    ],
    catalysts: [
      "Investor rotation to income in late economic cycle",
      "Rate cuts increasing relative attractiveness of dividend yields",
      "Constituent companies with strong free cash flow growing dividends",
    ],
    expenseRatio: 0.06,
    aum: "$65B",
    holdings: 100,
  },
  {
    ticker: "VIG",
    name: "Vanguard Dividend Appreciation ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 195.47,
    change: 0.83,
    changePercent: 0.43,
    marketCap: "$95B",
    peRatio: 23.5,
    dividendYield: 1.72,
    fiftyTwoHigh: 206.89,
    fiftyTwoLow: 166.23,
    analystRating: "Buy",
    aiScore: 79,
    beta: 0.82,
    description: "Tracks companies with 10+ consecutive years of dividend growth, emphasizing dividend sustainability",
    thesis:
      "Dividend growers outperform the broader market over full market cycles with lower drawdowns. The 10-year growth requirement filters for high-quality businesses with durable competitive advantages. Lower volatility than SPY.",
    risks: [
      "Lower current yield than SCHD limits appeal to income-focused investors",
      "Quality screen reduces universe to large established companies with limited upside",
      "Dividend growth can stall or reverse in severe recessions",
    ],
    catalysts: [
      "Quality factor premium in risk-off environments",
      "Dividend growers expanding payout ratios from strong earnings",
      "Defensive characteristics attractive as economic cycle matures",
    ],
    expenseRatio: 0.06,
    aum: "$95B",
    holdings: 289,
  },
  {
    ticker: "XLK",
    name: "Technology Select Sector SPDR Fund",
    sector: "Technology",
    type: "etf" as const,
    price: 226.14,
    change: 3.41,
    changePercent: 1.53,
    marketCap: "$72B",
    peRatio: 34.7,
    dividendYield: 0.64,
    fiftyTwoHigh: 255.60,
    fiftyTwoLow: 183.31,
    analystRating: "Buy",
    aiScore: 85,
    beta: 1.24,
    description: "Pure technology sector ETF holding S&P 500 tech stocks led by Apple, Nvidia, and Microsoft",
    thesis:
      "Direct exposure to the sector responsible for the majority of S&P 500 earnings growth. AI infrastructure spending benefits top three holdings simultaneously. Low 0.09% expense ratio for single-sector precision.",
    risks: [
      "Concentration risk -- Apple and Nvidia alone exceed 40% of fund weight",
      "Antitrust and regulatory actions targeting mega-cap tech",
      "High valuation multiples compress sharply if growth disappoints",
    ],
    catalysts: [
      "Nvidia data center revenue sustaining triple-digit growth",
      "Apple Intelligence feature set driving device upgrade cycle",
      "Enterprise AI software adoption expanding Microsoft Azure revenue",
    ],
    expenseRatio: 0.09,
    aum: "$72B",
    holdings: 67,
  },
  {
    ticker: "XLF",
    name: "Financial Select Sector SPDR Fund",
    sector: "Finance",
    type: "etf" as const,
    price: 48.73,
    change: 0.34,
    changePercent: 0.70,
    marketCap: "$48B",
    peRatio: 17.2,
    dividendYield: 1.53,
    fiftyTwoHigh: 53.04,
    fiftyTwoLow: 37.97,
    analystRating: "Buy",
    aiScore: 77,
    beta: 1.11,
    description: "S&P 500 financials sector ETF holding banks, insurers, asset managers, and payment networks",
    thesis:
      "Financial sector trades at compelling valuations relative to the market. Steeper yield curve improves net interest margins at banks. Deregulatory environment under current administration benefits M&A activity and capital returns.",
    risks: [
      "Credit quality deterioration if unemployment rises",
      "Inverted or flat yield curve compresses bank net interest margins",
      "Regulatory capital requirements could limit shareholder returns",
    ],
    catalysts: [
      "Yield curve steepening expanding bank profitability",
      "M&A wave from reduced regulatory friction boosting investment banking fees",
      "Loan growth recovery as businesses resume capital investment",
    ],
    expenseRatio: 0.09,
    aum: "$48B",
    holdings: 72,
  },
  {
    ticker: "XLE",
    name: "Energy Select Sector SPDR Fund",
    sector: "Energy",
    type: "etf" as const,
    price: 93.28,
    change: -0.61,
    changePercent: -0.65,
    marketCap: "$38B",
    peRatio: 14.1,
    dividendYield: 3.21,
    fiftyTwoHigh: 101.65,
    fiftyTwoLow: 78.43,
    analystRating: "Hold",
    aiScore: 72,
    beta: 0.97,
    description: "S&P 500 energy sector ETF dominated by ExxonMobil and Chevron with oil and gas exposure",
    thesis:
      "Energy sector generates strong free cash flow at current oil prices. Attractive dividend yield with ongoing buyback programs. Supply discipline from OPEC and reduced US drilling capex supports oil prices structurally.",
    risks: [
      "Oil price volatility from geopolitical supply disruptions or demand slowdowns",
      "Energy transition secular headwinds as EVs displace oil demand long term",
      "Concentration in two names -- Exxon and Chevron comprise 45%+ of the fund",
    ],
    catalysts: [
      "Sustained oil prices above $75 driving free cash flow and buybacks",
      "LNG export infrastructure buildout expanding gas revenue",
      "Geopolitical supply disruptions tightening global oil market",
    ],
    expenseRatio: 0.09,
    aum: "$38B",
    holdings: 23,
  },
  {
    ticker: "XLV",
    name: "Health Care Select Sector SPDR Fund",
    sector: "Healthcare",
    type: "etf" as const,
    price: 148.92,
    change: 0.47,
    changePercent: 0.32,
    marketCap: "$40B",
    peRatio: 21.3,
    dividendYield: 1.54,
    fiftyTwoHigh: 161.55,
    fiftyTwoLow: 127.21,
    analystRating: "Buy",
    aiScore: 78,
    beta: 0.66,
    description: "S&P 500 healthcare sector ETF covering pharma, biotech, medical devices, and managed care",
    thesis:
      "Defensive sector with inelastic demand growing alongside aging demographics. GLP-1 drug revolution at Eli Lilly creates sustained earnings growth. Medical devices and diagnostics benefit from post-pandemic procedure recovery.",
    risks: [
      "Drug pricing policy risk from Medicare negotiation expansion",
      "Patent cliffs at major pharma companies creating earnings gaps",
      "Biotech volatility from clinical trial failures affecting sector sentiment",
    ],
    catalysts: [
      "GLP-1 obesity drug adoption expanding total addressable markets",
      "Aging baby boomer cohort accelerating healthcare utilization",
      "AI drug discovery reducing R&D timelines and costs",
    ],
    expenseRatio: 0.09,
    aum: "$40B",
    holdings: 63,
  },
  {
    ticker: "VWO",
    name: "Vanguard FTSE Emerging Markets ETF",
    sector: "International",
    type: "etf" as const,
    price: 44.81,
    change: -0.23,
    changePercent: -0.51,
    marketCap: "$82B",
    peRatio: 13.6,
    dividendYield: 2.97,
    fiftyTwoHigh: 48.77,
    fiftyTwoLow: 37.50,
    analystRating: "Hold",
    aiScore: 70,
    beta: 0.84,
    description: "Tracks the FTSE Emerging Markets All Cap China A Inclusion Index across 24 countries",
    thesis:
      "Emerging markets trade at the widest valuation discount to US equities in two decades. China stimulus policy could trigger significant re-rating. Demographics and middle class growth in India and Southeast Asia drive long-run demand.",
    risks: [
      "China makes up 30%+ of the fund and faces geopolitical and regulatory uncertainty",
      "Strong US dollar is a structural headwind for dollar-denominated EM returns",
      "Political instability and capital controls in select EM economies",
    ],
    catalysts: [
      "China consumer stimulus triggering broad EM equity re-rating",
      "Indian equity market compounding as the world's fastest growing large economy",
      "US dollar weakening boosting local currency returns for US investors",
    ],
    expenseRatio: 0.08,
    aum: "$82B",
    holdings: 5858,
  },
  {
    ticker: "VXUS",
    name: "Vanguard Total International Stock ETF",
    sector: "International",
    type: "etf" as const,
    price: 61.34,
    change: -0.19,
    changePercent: -0.31,
    marketCap: "$75B",
    peRatio: 14.8,
    dividendYield: 3.11,
    fiftyTwoHigh: 67.47,
    fiftyTwoLow: 51.26,
    analystRating: "Hold",
    aiScore: 71,
    beta: 0.87,
    description: "Owns every non-US equity across developed and emerging markets in a single fund",
    thesis:
      "International equities offer compelling value at 14x earnings versus 25x for the S&P 500. Geographic diversification reduces dependence on any single economy. Paired with VTI, creates a complete global equity portfolio.",
    risks: [
      "US dollar strength erodes returns from foreign currency assets",
      "European economic stagnation weighs on developed market performance",
      "China exposure introduces geopolitical concentration risk",
    ],
    catalysts: [
      "Dollar cycle peak and reversal amplifying international equity returns",
      "Valuation mean reversion from extreme US-vs-world gap",
      "European fiscal stimulus packages reigniting growth",
    ],
    expenseRatio: 0.07,
    aum: "$75B",
    holdings: 8550,
  },
  {
    ticker: "BND",
    name: "Vanguard Total Bond Market ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 73.48,
    change: 0.11,
    changePercent: 0.15,
    marketCap: "$120B",
    peRatio: 0,
    dividendYield: 4.42,
    fiftyTwoHigh: 75.42,
    fiftyTwoLow: 70.87,
    analystRating: "Buy",
    aiScore: 75,
    beta: 0.04,
    description: "Tracks the Bloomberg US Aggregate Bond Index covering investment-grade US bonds",
    thesis:
      "Core fixed income exposure at 0.03% expense ratio. Provides portfolio ballast against equity market volatility. Near 4.4% yield is attractive relative to 10-year historical averages and beats cash once rates normalize lower.",
    risks: [
      "Duration risk -- rising rates push bond prices down",
      "Inflation reacceleration erodes real returns from fixed income",
      "Government debt expansion pressuring long-end yields higher",
    ],
    catalysts: [
      "Fed rate cut cycle beginning creates price appreciation from duration",
      "Flight to quality during equity market stress drives demand",
      "Yield lock-in at current levels attractive if rates decline",
    ],
    expenseRatio: 0.03,
    aum: "$120B",
    holdings: 17514,
  },
  {
    ticker: "AGG",
    name: "iShares Core US Aggregate Bond ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 96.71,
    change: 0.14,
    changePercent: 0.14,
    marketCap: "$108B",
    peRatio: 0,
    dividendYield: 4.38,
    fiftyTwoHigh: 99.04,
    fiftyTwoLow: 93.32,
    analystRating: "Buy",
    aiScore: 74,
    beta: 0.04,
    description: "iShares equivalent of BND tracking the Bloomberg US Aggregate Bond Index",
    thesis:
      "Institutional standard for US core fixed income. More widely used than BND in institutional portfolios, offering superior liquidity for large trades. Identical index exposure makes the choice between BND and AGG purely about cost and liquidity needs.",
    risks: [
      "Rate duration creates mark-to-market losses if yields rise further",
      "Government and agency bonds dominate -- limited credit yield pickup",
      "Inflation erodes purchasing power of fixed coupon payments",
    ],
    catalysts: [
      "Fed rate cuts boosting total return through price appreciation",
      "Recession fears increasing safe-haven demand for investment-grade bonds",
      "Corporate bond spread compression in improving credit environments",
    ],
    expenseRatio: 0.03,
    aum: "$108B",
    holdings: 11730,
  },
  {
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 87.43,
    change: 0.62,
    changePercent: 0.71,
    marketCap: "$52B",
    peRatio: 0,
    dividendYield: 4.71,
    fiftyTwoHigh: 101.22,
    fiftyTwoLow: 82.42,
    analystRating: "Hold",
    aiScore: 70,
    beta: -0.22,
    description: "Tracks long-dated US Treasury bonds with maturities of 20 years or more",
    thesis:
      "Highest duration Treasury ETF offering maximum price appreciation in a falling rate environment. Negative beta provides genuine portfolio hedging versus equity drawdowns. Near 4.7% yield with government backing.",
    risks: [
      "Extreme duration -- each 1% rate rise causes approximately 17% price decline",
      "Fiscal deficit expansion could structurally keep long rates elevated",
      "Inflation regime shift from supply-side factors limiting Fed cut scope",
    ],
    catalysts: [
      "Recession or growth scare triggering aggressive Fed rate cuts",
      "Flight to safety bid in geopolitical or financial market crises",
      "Inflation returning to target enabling Fed to ease at long end",
    ],
    expenseRatio: 0.15,
    aum: "$52B",
    holdings: 41,
  },
  {
    ticker: "GLD",
    name: "SPDR Gold Shares",
    sector: "Broad Market",
    type: "etf" as const,
    price: 241.87,
    change: 1.43,
    changePercent: 0.59,
    marketCap: "$76B",
    peRatio: 0,
    dividendYield: 0,
    fiftyTwoHigh: 261.30,
    fiftyTwoLow: 181.60,
    analystRating: "Buy",
    aiScore: 77,
    beta: 0.09,
    description: "Physical gold bullion ETF where each share represents approximately 1/10th of an ounce of gold",
    thesis:
      "Gold at all-time highs driven by central bank accumulation, geopolitical demand, and dollar diversification. Functions as portfolio insurance against tail risks including inflation, currency debasement, and geopolitical crises. Central bank buying provides structural floor.",
    risks: [
      "No yield -- opportunity cost relative to 4%+ cash rates",
      "Strong dollar is historically a headwind for gold prices",
      "Gold price tied to real interest rates -- rising real yields pressure price",
    ],
    catalysts: [
      "Central bank gold purchases at multi-decade highs providing demand floor",
      "Dollar weakening and real rate declines as Fed eases",
      "Geopolitical risk premium as a safe-haven asset in unstable environment",
    ],
    expenseRatio: 0.4,
    aum: "$76B",
    holdings: 1,
  },
  {
    ticker: "ARKK",
    name: "ARK Innovation ETF",
    sector: "Technology",
    type: "etf" as const,
    price: 51.24,
    change: 0.89,
    changePercent: 1.77,
    marketCap: "$7B",
    peRatio: 68.2,
    dividendYield: 0,
    fiftyTwoHigh: 63.17,
    fiftyTwoLow: 37.08,
    analystRating: "Hold",
    aiScore: 71,
    beta: 1.58,
    description: "Actively managed ETF targeting disruptive innovation across AI, genomics, fintech, and space",
    thesis:
      "High-conviction concentrated bets on companies Cathie Wood believes will define the next decade. Invests early in platforms like Tesla, Coinbase, and UiPath before institutional consensus. High-risk exposure to exponential technology themes.",
    risks: [
      "Concentrated in speculative high-multiple companies with no current earnings",
      "High fee (0.75%) for active management that has underperformed passive since 2021",
      "Liquidity mismatch -- large redemptions force selling of illiquid positions at poor prices",
    ],
    catalysts: [
      "AI adoption acceleration validating portfolio company revenue models",
      "Rate cuts expanding multiples on long-duration growth assets",
      "Bitcoin and crypto rally lifting Coinbase and crypto-adjacent holdings",
    ],
    expenseRatio: 0.75,
    aum: "$7B",
    holdings: 29,
  },
  {
    ticker: "XLI",
    name: "Industrial Select Sector SPDR Fund",
    sector: "Industrial",
    type: "etf" as const,
    price: 134.22,
    change: 0.68,
    changePercent: 0.51,
    marketCap: "$21B",
    peRatio: 21.4,
    dividendYield: 1.48,
    fiftyTwoHigh: 141.77,
    fiftyTwoLow: 107.82,
    analystRating: "Buy",
    aiScore: 76,
    beta: 1.04,
    description: "S&P 500 industrials sector ETF covering aerospace, defense, machinery, and transportation companies",
    thesis:
      "US industrial sector benefits from reshoring of manufacturing, elevated defense budgets, and infrastructure spending. Aerospace cycle recovery post-pandemic continues with Boeing and GE Aerospace driving earnings. Low 0.09% expense ratio for clean sector exposure.",
    risks: [
      "Economic slowdown reduces capital equipment orders and freight volumes",
      "Input cost inflation from steel and aluminum tariffs compressing margins",
      "Defense budget cuts from fiscal austerity measures",
    ],
    catalysts: [
      "Infrastructure Investment and Jobs Act driving multi-year construction and equipment demand",
      "Aerospace backlog at Boeing and Airbus sustaining production ramp-through 2027",
      "Reshoring and nearshoring capex cycle benefiting domestic manufacturers",
    ],
    expenseRatio: 0.09,
    aum: "$21B",
    holdings: 78,
  },
  {
    ticker: "XLC",
    name: "Communication Services Select Sector SPDR Fund",
    sector: "Communication",
    type: "etf" as const,
    price: 96.87,
    change: 1.14,
    changePercent: 1.19,
    marketCap: "$18B",
    peRatio: 22.6,
    dividendYield: 0.81,
    fiftyTwoHigh: 107.44,
    fiftyTwoLow: 73.51,
    analystRating: "Buy",
    aiScore: 80,
    beta: 1.12,
    description: "S&P 500 communication services sector ETF led by Alphabet, Meta, and Netflix",
    thesis:
      "Communication services holds the two largest digital advertising platforms alongside the dominant streaming business. Alphabet and Meta generate exceptional free cash flow being directed into AI infrastructure that strengthens their advertising moats. Reasonable 22x earnings for the growth profile.",
    risks: [
      "Antitrust actions targeting Google Search and Meta's ad network",
      "Ad market cyclicality creates revenue volatility in economic downturns",
      "Streaming competition intensifying content cost inflation at Netflix",
    ],
    catalysts: [
      "AI-powered ad targeting improving conversion rates and pricing at Alphabet and Meta",
      "YouTube and Instagram Reels monetization expanding total addressable market",
      "Streaming profitability inflection as subscriber growth normalizes",
    ],
    expenseRatio: 0.09,
    aum: "$18B",
    holdings: 22,
  },
  {
    ticker: "XLY",
    name: "Consumer Discretionary Select Sector SPDR Fund",
    sector: "Consumer",
    type: "etf" as const,
    price: 202.45,
    change: 2.31,
    changePercent: 1.15,
    marketCap: "$22B",
    peRatio: 30.1,
    dividendYield: 0.74,
    fiftyTwoHigh: 220.16,
    fiftyTwoLow: 153.78,
    analystRating: "Hold",
    aiScore: 73,
    beta: 1.28,
    description: "S&P 500 consumer discretionary sector ETF dominated by Amazon and Tesla",
    thesis:
      "Amazon and Tesla together exceed 40% of the fund, providing indirect high-growth tech exposure labeled as consumer. Amazon Web Services drives the majority of Amazon earnings while its retail flywheel continues gaining share. High beta vehicle for risk-on consumer spending environments.",
    risks: [
      "Consumer spending softness from elevated debt burdens and slowing job growth",
      "Tesla faces intensifying EV competition from Chinese manufacturers and legacy automakers",
      "High concentration in two names creates idiosyncratic single-stock risk",
    ],
    catalysts: [
      "Amazon AWS revenue acceleration and margin expansion driving earnings beat",
      "Consumer confidence recovery from rate normalization boosting discretionary spending",
      "Tesla Full Self-Driving commercialization adding robotaxi revenue stream",
    ],
    expenseRatio: 0.09,
    aum: "$22B",
    holdings: 51,
  },
  {
    ticker: "XLP",
    name: "Consumer Staples Select Sector SPDR Fund",
    sector: "Consumer",
    type: "etf" as const,
    price: 79.34,
    change: 0.22,
    changePercent: 0.28,
    marketCap: "$15B",
    peRatio: 22.8,
    dividendYield: 2.71,
    fiftyTwoHigh: 82.65,
    fiftyTwoLow: 68.93,
    analystRating: "Hold",
    aiScore: 72,
    beta: 0.57,
    description: "S&P 500 consumer staples sector ETF holding food, beverage, household products, and retail staples",
    thesis:
      "Defensive anchor with pricing power in inflationary environments. Procter and Gamble, Costco, and Walmart form a core of businesses with durable competitive advantages and reliable dividend histories. Performs best during equity market stress.",
    risks: [
      "Volume pressure as consumers trade down from brand-name to private label",
      "Stretched valuations at 22x earnings for slow-growth businesses",
      "Higher rates reduce appeal of dividend stocks relative to bonds",
    ],
    catalysts: [
      "Defensive rotation as economic cycle matures and recession probability rises",
      "Pricing power recovery after years of cost-push inflation normalizes margins",
      "Dividend growth from strong free cash flow sustaining income-focused buyer demand",
    ],
    expenseRatio: 0.09,
    aum: "$15B",
    holdings: 38,
  },
  {
    ticker: "XLB",
    name: "Materials Select Sector SPDR Fund",
    sector: "Materials",
    type: "etf" as const,
    price: 88.76,
    change: 0.43,
    changePercent: 0.49,
    marketCap: "$7B",
    peRatio: 20.5,
    dividendYield: 1.92,
    fiftyTwoHigh: 97.30,
    fiftyTwoLow: 74.48,
    analystRating: "Hold",
    aiScore: 71,
    beta: 1.02,
    description: "S&P 500 materials sector ETF covering chemicals, metals, mining, and packaging companies",
    thesis:
      "Materials sector benefits from the green energy transition requiring unprecedented quantities of copper, lithium, and rare earths. Infrastructure spending and data center construction drive demand for steel and specialty chemicals. Inflation hedge with real asset backing.",
    risks: [
      "Global growth slowdown reducing industrial metals demand from China",
      "US dollar strength making dollar-priced commodities more expensive abroad",
      "Commodity price cyclicality creates earnings volatility across the portfolio",
    ],
    catalysts: [
      "Copper demand surge from EV batteries, grid electrification, and data center buildout",
      "China construction recovery lifting steel and cement prices",
      "Critical minerals supply constraints tightening as EV adoption scales globally",
    ],
    expenseRatio: 0.09,
    aum: "$7B",
    holdings: 29,
  },
  {
    ticker: "XLRE",
    name: "Real Estate Select Sector SPDR Fund",
    sector: "Real Estate",
    type: "etf" as const,
    price: 41.87,
    change: 0.31,
    changePercent: 0.75,
    marketCap: "$7B",
    peRatio: 33.2,
    dividendYield: 3.58,
    fiftyTwoHigh: 45.62,
    fiftyTwoLow: 33.41,
    analystRating: "Hold",
    aiScore: 70,
    beta: 0.82,
    description: "S&P 500 real estate sector ETF holding REITs across data centers, industrial, retail, and residential properties",
    thesis:
      "REITs are among the most rate-sensitive assets in the market, positioning XLRE for strong returns as the Fed cuts rates. Data center REITs like Equinix and Iron Mountain benefit from AI infrastructure buildout directly. 3.5%+ yield with dividend growth.",
    risks: [
      "Rates staying higher for longer compresses REIT valuations and refinancing costs",
      "Office REIT exposure faces structural demand decline from remote work",
      "Leverage-heavy balance sheets vulnerable to credit market tightening",
    ],
    catalysts: [
      "Fed rate cut cycle reducing REIT cost of capital and expanding valuations",
      "Data center REIT demand growth from AI infrastructure buildout",
      "Industrial REIT rent growth driven by e-commerce logistics demand",
    ],
    expenseRatio: 0.09,
    aum: "$7B",
    holdings: 31,
  },
  {
    ticker: "XLU",
    name: "Utilities Select Sector SPDR Fund",
    sector: "Utilities",
    type: "etf" as const,
    price: 79.18,
    change: 0.37,
    changePercent: 0.47,
    marketCap: "$15B",
    peRatio: 19.7,
    dividendYield: 2.91,
    fiftyTwoHigh: 83.88,
    fiftyTwoLow: 60.42,
    analystRating: "Buy",
    aiScore: 74,
    beta: 0.36,
    description: "S&P 500 utilities sector ETF holding electric, gas, and water utilities with regulated earnings",
    thesis:
      "Utilities re-rated sharply higher as the most direct beneficiary of AI data center power demand. NextEra and Constellation Energy are adding gigawatts of capacity for hyperscaler power purchase agreements. Regulated earnings provide downside stability while growth catalysts are above-trend.",
    risks: [
      "Interest rate sensitivity -- utilities behave like long-duration bonds",
      "Data center power demand growth slower than current market expectations",
      "Regulatory approval delays and cost overruns on new generation projects",
    ],
    catalysts: [
      "Hyperscaler power purchase agreements locking in multi-decade revenue for grid operators",
      "Nuclear energy renaissance driven by AI data center clean power mandates",
      "Fed rate cuts reducing borrowing costs for capital-intensive utility expansion",
    ],
    expenseRatio: 0.09,
    aum: "$15B",
    holdings: 31,
  },
  {
    ticker: "DGRO",
    name: "iShares Core Dividend Growth ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 59.43,
    change: 0.27,
    changePercent: 0.46,
    marketCap: "$28B",
    peRatio: 20.1,
    dividendYield: 2.31,
    fiftyTwoHigh: 63.17,
    fiftyTwoLow: 51.89,
    analystRating: "Buy",
    aiScore: 78,
    beta: 0.76,
    description: "Tracks US equities with at least five consecutive years of dividend growth and positive earnings",
    thesis:
      "DGRO combines the dividend growth quality screen with a lower expense ratio than VIG at 0.08%. The five-year growth requirement captures companies earlier in their dividend growth lifecycle, adding more mid-cap quality companies. Historically outperforms the S&P 500 on a risk-adjusted basis.",
    risks: [
      "Quality tilt underperforms in speculative bull markets driven by unprofitable growth",
      "Rising rates create headwinds for dividend-paying stocks valued on yield",
      "Dividend cuts during recessions reduce income and trigger negative rerating",
    ],
    catalysts: [
      "Late cycle defensive rotation into quality dividend growers",
      "Rate cuts increasing relative attractiveness of 2.3% growing yield",
      "Strong free cash flow generation at constituent companies accelerating payout growth",
    ],
    expenseRatio: 0.08,
    aum: "$28B",
    holdings: 432,
  },
  {
    ticker: "MTUM",
    name: "iShares MSCI USA Momentum Factor ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 198.54,
    change: 2.17,
    changePercent: 1.10,
    marketCap: "$14B",
    peRatio: 29.3,
    dividendYield: 0.91,
    fiftyTwoHigh: 218.43,
    fiftyTwoLow: 161.27,
    analystRating: "Buy",
    aiScore: 79,
    beta: 1.07,
    description: "Tracks large and mid-cap US stocks exhibiting strong relative price momentum over 6 and 12 months",
    thesis:
      "Momentum is one of the best-documented return factors in academic finance. MTUM systematically captures stocks in uptrends, rotating into new leaders twice per year. Outperforms in trending bull markets and underperforms significantly only at factor reversal inflection points.",
    risks: [
      "Momentum crashes can be severe and rapid during market regime shifts",
      "Rebalance periods create predictable front-running from other traders",
      "Currently concentrated in the same mega-cap tech names as QQQ",
    ],
    catalysts: [
      "Trending equity market environment extending momentum factor outperformance",
      "AI theme continuation sustaining technology sector price leadership",
      "Factor persistence historically strongest in low-volatility trending markets",
    ],
    expenseRatio: 0.15,
    aum: "$14B",
    holdings: 125,
  },
  {
    ticker: "EFA",
    name: "iShares MSCI EAFE ETF",
    sector: "International",
    type: "etf" as const,
    price: 80.43,
    change: -0.31,
    changePercent: -0.38,
    marketCap: "$50B",
    peRatio: 15.2,
    dividendYield: 3.22,
    fiftyTwoHigh: 87.15,
    fiftyTwoLow: 66.94,
    analystRating: "Hold",
    aiScore: 69,
    beta: 0.82,
    description: "Tracks the MSCI EAFE index covering developed market equities in Europe, Australasia, and the Far East",
    thesis:
      "EAFE offers broad developed market exposure at 15x earnings versus 25x for US equities. Japan, UK, and European stocks trade at historically wide discounts to US peers and offer 3.2% dividend yields. Currency tailwinds possible as dollar cycle turns.",
    risks: [
      "European economic stagnation from energy crisis and weak German industrial output",
      "Strong US dollar reduces foreign currency returns for US-based investors",
      "Japan monetary policy normalization creating headwinds for domestic equities",
    ],
    catalysts: [
      "Dollar cycle peak enabling currency tailwind for international equity returns",
      "European fiscal spending programs reigniting growth across the continent",
      "Japan corporate governance reforms unlocking shareholder value at undervalued companies",
    ],
    expenseRatio: 0.32,
    aum: "$50B",
    holdings: 788,
  },
  {
    ticker: "INDA",
    name: "iShares MSCI India ETF",
    sector: "International",
    type: "etf" as const,
    price: 52.87,
    change: 0.63,
    changePercent: 1.21,
    marketCap: "$9B",
    peRatio: 23.4,
    dividendYield: 0.42,
    fiftyTwoHigh: 60.11,
    fiftyTwoLow: 42.68,
    analystRating: "Buy",
    aiScore: 81,
    beta: 0.71,
    description: "Tracks large and mid-cap Indian equities across the MSCI India index",
    thesis:
      "India is the world's fastest growing major economy, projected to become the third largest by 2030. Demographic dividend with median age of 28 years creates sustained domestic consumption growth. Digital infrastructure buildout and manufacturing reshoring from China are structural tailwinds.",
    risks: [
      "Elevated 23x PE premium to other emerging markets limits upside from valuation expansion",
      "Currency risk from Indian rupee depreciation against the US dollar",
      "Political and regulatory uncertainty in a fast-changing regulatory environment",
    ],
    catalysts: [
      "GDP growth sustaining 7%+ annually driving corporate earnings compounding",
      "Foreign direct investment inflows from supply chain diversification away from China",
      "Indian consumer class expansion powering domestic financial services and consumption",
    ],
    expenseRatio: 0.65,
    aum: "$9B",
    holdings: 138,
  },
  {
    ticker: "MCHI",
    name: "iShares MSCI China ETF",
    sector: "International",
    type: "etf" as const,
    price: 48.62,
    change: 0.91,
    changePercent: 1.91,
    marketCap: "$7B",
    peRatio: 13.1,
    dividendYield: 1.87,
    fiftyTwoHigh: 57.44,
    fiftyTwoLow: 34.22,
    analystRating: "Hold",
    aiScore: 66,
    beta: 0.63,
    description: "Tracks large and mid-cap Chinese equities listed in mainland China, Hong Kong, and the US",
    thesis:
      "Chinese equities trade at 13x earnings with significant stimulus optionality. Government has signaled willingness to deploy fiscal stimulus to support growth and property sector stabilization. Deep value opportunity if policy credibility is restored and geopolitical tensions de-escalate.",
    risks: [
      "US-China geopolitical tensions escalating toward financial decoupling or sanctions",
      "Regulatory crackdowns on technology, education, and financial sectors",
      "Property sector debt overhang weighing on consumer confidence and bank balance sheets",
    ],
    catalysts: [
      "Large-scale Chinese fiscal stimulus package exceeding market expectations",
      "Property market stabilization restoring household wealth and consumer confidence",
      "DeepSeek and domestic AI ecosystem development validating Chinese tech competitiveness",
    ],
    expenseRatio: 0.59,
    aum: "$7B",
    holdings: 601,
  },
  {
    ticker: "HYG",
    name: "iShares iBoxx High Yield Corporate Bond ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 77.84,
    change: 0.09,
    changePercent: 0.12,
    marketCap: "$16B",
    peRatio: 0,
    dividendYield: 6.42,
    fiftyTwoHigh: 80.11,
    fiftyTwoLow: 74.98,
    analystRating: "Hold",
    aiScore: 68,
    beta: 0.48,
    description: "Tracks the investment performance of the broad US high yield corporate bond market",
    thesis:
      "High yield bonds offer 6.4% income yield in a world where equity dividend yields average 1.5%. Default rates remain below historical averages given strong corporate balance sheets built during zero rate era. Spreads over Treasuries compensate for credit risk at current levels.",
    risks: [
      "Credit spreads widen sharply in recession as defaults accelerate",
      "Correlation with equities increases in risk-off environments, reducing diversification benefit",
      "Liquidity deteriorates significantly during market stress events",
    ],
    catalysts: [
      "Soft landing economic scenario keeping default rates below historical averages",
      "Rate cuts tightening credit spreads as refinancing risk declines",
      "Income-seeking investor demand with 6%+ yield in normalized rate environment",
    ],
    expenseRatio: 0.49,
    aum: "$16B",
    holdings: 1231,
  },
  {
    ticker: "TIP",
    name: "iShares TIPS Bond ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 107.23,
    change: 0.18,
    changePercent: 0.17,
    marketCap: "$16B",
    peRatio: 0,
    dividendYield: 3.87,
    fiftyTwoHigh: 110.44,
    fiftyTwoLow: 103.76,
    analystRating: "Hold",
    aiScore: 72,
    beta: 0.07,
    description: "Tracks US Treasury Inflation-Protected Securities, with principal adjusting with the Consumer Price Index",
    thesis:
      "TIPS provide explicit inflation insurance unavailable in nominal Treasury bonds. If inflation resurges above market expectations, TIPS outperform both nominal bonds and most equities. Near 3.9% real yield after inflation adjustment is near historic highs.",
    risks: [
      "Deflation or sharply declining inflation reduces TIPS price return versus nominal bonds",
      "Duration risk means principal can decline if real interest rates rise",
      "Lower nominal yield than comparable maturity Treasury bonds in normal inflation environments",
    ],
    catalysts: [
      "Inflation resurgence from tariff pass-through or supply disruptions validating inflation protection",
      "Real yield normalization lower as Fed cuts rates driving price appreciation",
      "Portfolio insurance demand from investors concerned about fiscal deficit inflation pressures",
    ],
    expenseRatio: 0.19,
    aum: "$16B",
    holdings: 51,
  },
  {
    ticker: "SLV",
    name: "iShares Silver Trust",
    sector: "Broad Market",
    type: "etf" as const,
    price: 28.74,
    change: 0.34,
    changePercent: 1.20,
    marketCap: "$14B",
    peRatio: 0,
    dividendYield: 0,
    fiftyTwoHigh: 34.22,
    fiftyTwoLow: 20.64,
    analystRating: "Buy",
    aiScore: 74,
    beta: 0.52,
    description: "Physical silver bullion ETF holding silver bars in allocated vaults, tracking the silver spot price",
    thesis:
      "Silver has dual demand as both a monetary metal and an industrial input for solar panels, electronics, and EV components. Solar panel installation globally requires 100+ million ounces of silver annually with limited mining supply response. Historically outperforms gold in bull commodity cycles.",
    risks: [
      "More volatile than gold with larger drawdowns in risk-off environments",
      "Industrial demand contraction in global recession reduces silver consumption",
      "No yield creates significant opportunity cost versus 4%+ fixed income alternatives",
    ],
    catalysts: [
      "Solar energy buildout consuming structural industrial silver demand above mining supply",
      "Gold breakout historically precedes silver outperformance by 6-12 months",
      "Dollar weakening and real rate declines boosting monetary metals broadly",
    ],
    expenseRatio: 0.5,
    aum: "$14B",
    holdings: 1,
  },
  {
    ticker: "VNQ",
    name: "Vanguard Real Estate ETF",
    sector: "Real Estate",
    type: "etf" as const,
    price: 87.63,
    change: 0.64,
    changePercent: 0.74,
    marketCap: "$36B",
    peRatio: 35.1,
    dividendYield: 4.13,
    fiftyTwoHigh: 95.18,
    fiftyTwoLow: 70.91,
    analystRating: "Buy",
    aiScore: 73,
    beta: 0.84,
    description: "Tracks the MSCI US Investable Market Real Estate 25/50 Index across all real estate investment trusts",
    thesis:
      "REITs are required to distribute 90% of taxable income, creating a durable 4%+ yield with inflation-linked rent growth. Vanguard's 0.13% expense ratio is lowest in the REIT ETF category. Rate cut cycle creates the most favorable REIT environment since 2020.",
    risks: [
      "Rate sensitivity -- each 100bps increase in long rates reduces REIT valuations materially",
      "Office REIT exposure faces secular decline from hybrid work permanence",
      "Highly leveraged balance sheets amplify downside during credit tightening",
    ],
    catalysts: [
      "Fed rate cut cycle dramatically reducing REIT cost of capital and refinancing burden",
      "Data center and industrial REIT demand sustained by e-commerce and AI infrastructure",
      "Housing scarcity supporting apartment REIT pricing power and occupancy rates",
    ],
    expenseRatio: 0.13,
    aum: "$36B",
    holdings: 160,
  },
  {
    ticker: "BITO",
    name: "ProShares Bitcoin Strategy ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 26.43,
    change: 0.88,
    changePercent: 3.45,
    marketCap: "$2B",
    peRatio: 0,
    dividendYield: 0,
    fiftyTwoHigh: 38.91,
    fiftyTwoLow: 17.22,
    analystRating: "Hold",
    aiScore: 65,
    beta: 1.74,
    description: "First US Bitcoin futures ETF providing regulated exposure to Bitcoin price movements in a brokerage account",
    thesis:
      "Accessible regulated wrapper for Bitcoin exposure without wallet custody requirements. Suitable for accounts that cannot hold spot Bitcoin ETFs. Bitcoin's fixed supply schedule and halving cycle historically produce multi-year bull markets with significant upside from current levels.",
    risks: [
      "Futures roll costs create significant negative tracking versus spot Bitcoin price over time",
      "Extreme volatility -- Bitcoin regularly declines 70-80% from peak in bear markets",
      "Regulatory actions targeting crypto assets could impair fund operations",
    ],
    catalysts: [
      "Bitcoin halving reducing new supply issuance while institutional demand expands",
      "ETF-driven institutional allocation creating structural demand beyond retail buyers",
      "Macro dollar debasement narrative driving Bitcoin as digital store of value",
    ],
    expenseRatio: 0.95,
    aum: "$2B",
    holdings: 1,
  },
  {
    ticker: "HACK",
    name: "ETFMG Prime Cyber Security ETF",
    sector: "Technology",
    type: "etf" as const,
    price: 62.18,
    change: 0.74,
    changePercent: 1.20,
    marketCap: "$1.5B",
    peRatio: 38.4,
    dividendYield: 0.31,
    fiftyTwoHigh: 68.44,
    fiftyTwoLow: 49.77,
    analystRating: "Buy",
    aiScore: 78,
    beta: 1.09,
    description: "Tracks companies providing cybersecurity products and services including network, endpoint, and cloud security",
    thesis:
      "Cybersecurity spending is non-discretionary and grows regardless of economic conditions as threat volumes escalate. AI-powered attacks are forcing enterprises to upgrade to AI-native security platforms, benefiting CrowdStrike, Palo Alto, and Zscaler. Government and critical infrastructure mandates drive baseline spending floors.",
    risks: [
      "High valuations at 38x earnings require sustained revenue growth above 20%",
      "Vendor consolidation could reduce total addressable market for smaller players",
      "Cybersecurity fatigue and budget compression during enterprise cost-cutting cycles",
    ],
    catalysts: [
      "Escalating nation-state cyber attacks expanding enterprise and government security budgets",
      "AI-native security platform adoption cycle replacing legacy point solutions",
      "Regulatory mandates requiring enhanced cybersecurity controls across critical sectors",
    ],
    expenseRatio: 0.6,
    aum: "$1.5B",
    holdings: 59,
  },
  {
    ticker: "TAN",
    name: "Invesco Solar ETF",
    sector: "Energy",
    type: "etf" as const,
    price: 38.92,
    change: 0.56,
    changePercent: 1.46,
    marketCap: "$1.8B",
    peRatio: 18.6,
    dividendYield: 1.14,
    fiftyTwoHigh: 57.33,
    fiftyTwoLow: 31.44,
    analystRating: "Hold",
    aiScore: 67,
    beta: 1.33,
    description: "Tracks the MAC Global Solar Energy Index of solar energy companies across the value chain",
    thesis:
      "Solar is the cheapest source of new electricity generation in history and is growing at 30%+ annually. AI data center power demand is forcing utilities to accelerate clean energy procurement, and solar is the fastest-to-build option. Significant policy support via Inflation Reduction Act tax credits.",
    risks: [
      "Chinese solar panel overproduction driving module prices below profitability for Western manufacturers",
      "Policy risk from potential rollback or modification of IRA clean energy incentives",
      "Interest rate sensitivity -- solar projects are long-duration capital assets financed with debt",
    ],
    catalysts: [
      "AI data center power demand creating urgent solar procurement by hyperscalers",
      "IRA tax credits sustaining US solar installation growth through 2032",
      "Utility-scale solar cost declines making new projects economical at lower power prices",
    ],
    expenseRatio: 0.67,
    aum: "$1.8B",
    holdings: 41,
  },
  {
    ticker: "LIT",
    name: "Global X Lithium & Battery Tech ETF",
    sector: "Industrial",
    type: "etf" as const,
    price: 34.17,
    change: 0.48,
    changePercent: 1.42,
    marketCap: "$1.4B",
    peRatio: 17.2,
    dividendYield: 1.63,
    fiftyTwoHigh: 47.88,
    fiftyTwoLow: 27.56,
    analystRating: "Hold",
    aiScore: 68,
    beta: 1.18,
    description: "Tracks the Solactive Global Lithium Index covering lithium miners, refiners, and battery technology companies",
    thesis:
      "Lithium is the critical input for every EV battery and grid storage system built over the coming decade. Despite a 60%+ drawdown from peak, lithium demand projections remain intact as EV adoption accelerates globally. Current depressed prices are shaking out high-cost producers setting up for supply-demand tightening.",
    risks: [
      "Lithium price glut from Chinese spodumene oversupply pushing prices below miner breakeven",
      "EV demand growth below consensus projections reducing battery material consumption",
      "New battery chemistries like sodium-ion reducing lithium intensity per vehicle",
    ],
    catalysts: [
      "EV adoption inflection in the US and Europe driving lithium demand above current supply",
      "Grid-scale battery storage buildout for renewable energy intermittency creating new demand pool",
      "Supply rationalization from high-cost mine closures tightening lithium market balance",
    ],
    expenseRatio: 0.75,
    aum: "$1.4B",
    holdings: 40,
  },
];
