import { Stock } from "./stock-data";

export const etfUniverse: Stock[] = [
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    sector: "Broad Market",
    type: "etf" as const,
    price: 562.75,
    change: 4.23,
    changePercent: 0.76,
    marketCap: "$550B",
    peRatio: 25.8,
    dividendYield: 1.24,
    fiftyTwoHigh: 613.23,
    fiftyTwoLow: 480.57,
    analystRating: "Buy",
    aiScore: 84,
    beta: 1.0,
    description: "The original S&P 500 index ETF tracking 500 large-cap US equities by market cap weight",
    thesis:
      "Owning the 500 largest US companies in a single liquid vehicle. Decades of data show most active managers underperform SPY after fees. Core holding for any long-term equity portfolio.",
    risks: [
      "Top-heavy concentration in mega-cap tech (Apple, Nvidia, Microsoft make up 20%+)",
      "Full US market drawdowns with no downside buffer",
      "Currency and rate cycle sensitivity",
    ],
    catalysts: [
      "Continued earnings growth from mega-cap constituents",
      "Federal Reserve rate cuts expanding equity multiples",
      "Corporate buyback programs supporting index price",
    ],
    expenseRatio: 0.0945,
    aum: "$550B",
    holdings: 503,
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
    sector: "Technology",
    type: "etf" as const,
    price: 484.60,
    change: 5.12,
    changePercent: 1.07,
    marketCap: "$320B",
    peRatio: 31.4,
    dividendYield: 0.58,
    fiftyTwoHigh: 540.81,
    fiftyTwoLow: 400.44,
    analystRating: "Buy",
    aiScore: 86,
    beta: 1.19,
    description: "Tracks the Nasdaq-100 index, heavily weighted toward large-cap technology and growth companies",
    thesis:
      "Concentrated exposure to the highest-growth segment of the US equity market. AI, cloud, and semiconductor tailwinds benefit top holdings directly. Outperformed SPY over every 10-year rolling window since inception.",
    risks: [
      "High valuation multiples vulnerable to rate shock",
      "Mega-cap tech regulatory and antitrust risk",
      "No financial or energy sector exposure limits diversification",
    ],
    catalysts: [
      "AI-driven revenue acceleration at Microsoft, Nvidia, and Meta",
      "Continued margin expansion across software constituents",
      "Rate cuts disproportionately benefit long-duration growth names",
    ],
    expenseRatio: 0.2,
    aum: "$320B",
    holdings: 101,
  },
  {
    ticker: "VTI",
    name: "Vanguard Total Stock Market ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 278.34,
    change: 1.89,
    changePercent: 0.68,
    marketCap: "$450B",
    peRatio: 24.9,
    dividendYield: 1.31,
    fiftyTwoHigh: 303.65,
    fiftyTwoLow: 236.67,
    analystRating: "Buy",
    aiScore: 83,
    beta: 1.0,
    description: "Owns the entire US equity market across large, mid, and small caps in one fund",
    thesis:
      "Broader diversification than SPY by including mid and small caps. Vanguard's at-cost structure (0.03% expense ratio) means more of every dollar stays invested. True total market exposure in a single trade.",
    risks: [
      "Small and mid cap exposure adds volatility versus pure large-cap funds",
      "Correlated with entire US economy -- no defensive tilt",
      "Less liquid than SPY during stress events",
    ],
    catalysts: [
      "Small and mid cap valuation catch-up if rates decline",
      "Broad earnings recovery across all market cap bands",
      "Continued inflows from 401(k) default fund adoptions",
    ],
    expenseRatio: 0.03,
    aum: "$450B",
    holdings: 3680,
  },
  {
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 221.45,
    change: -0.87,
    changePercent: -0.39,
    marketCap: "$78B",
    peRatio: 27.6,
    dividendYield: 1.11,
    fiftyTwoHigh: 244.47,
    fiftyTwoLow: 185.33,
    analystRating: "Hold",
    aiScore: 74,
    beta: 1.22,
    description: "Tracks 2000 small-cap US stocks in the Russell 2000 index",
    thesis:
      "Small caps historically outperform large caps over 10+ year periods. Domestically focused businesses benefit most from lower interest rates and a strong US economy. Attractive valuations relative to large caps.",
    risks: [
      "Higher sensitivity to credit conditions -- many holdings carry floating rate debt",
      "Earnings quality lower than large caps with more unprofitable companies",
      "Underperformed large caps for over a decade creating momentum headwinds",
    ],
    catalysts: [
      "Fed rate cuts reducing borrowing costs for leveraged small-cap companies",
      "Domestic economic acceleration benefiting locally focused businesses",
      "Rotation from mega-cap concentration into small cap value",
    ],
    expenseRatio: 0.19,
    aum: "$78B",
    holdings: 1971,
  },
  {
    ticker: "VOO",
    name: "Vanguard S&P 500 ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 516.60,
    change: 3.88,
    changePercent: 0.76,
    marketCap: "$570B",
    peRatio: 25.8,
    dividendYield: 1.27,
    fiftyTwoHigh: 563.03,
    fiftyTwoLow: 441.35,
    analystRating: "Buy",
    aiScore: 85,
    beta: 1.0,
    description: "Vanguard's S&P 500 fund offering the same index exposure as SPY at a fraction of the cost",
    thesis:
      "Functionally identical to SPY but with an 0.03% expense ratio versus 0.0945% for SPY. Long-term cost compounding makes VOO materially superior for buy-and-hold investors. Vanguard's ownership structure aligns incentives with shareholders.",
    risks: [
      "Same concentration risk as SPY in mega-cap technology",
      "Full participation in market drawdowns without any buffer",
      "Less intraday liquidity than SPY for large institutional trades",
    ],
    catalysts: [
      "S&P 500 earnings growth driven by AI infrastructure buildout",
      "Passive fund inflows creating structural buying pressure",
      "Buyback activity from cash-rich index members",
    ],
    expenseRatio: 0.03,
    aum: "$570B",
    holdings: 503,
  },
  {
    ticker: "VUG",
    name: "Vanguard Growth ETF",
    sector: "Technology",
    type: "etf" as const,
    price: 373.82,
    change: 3.94,
    changePercent: 1.07,
    marketCap: "$155B",
    peRatio: 34.2,
    dividendYield: 0.49,
    fiftyTwoHigh: 416.00,
    fiftyTwoLow: 305.56,
    analystRating: "Buy",
    aiScore: 82,
    beta: 1.14,
    description: "Tracks US large-cap growth stocks screened for earnings and revenue growth characteristics",
    thesis:
      "Pure-play on US growth at Vanguard's rock-bottom 0.04% expense ratio. Top holdings are the same AI-era compounders that have driven a decade of equity returns. Superior long-run returns to value in low-inflation environments.",
    risks: [
      "High duration risk -- growth stocks hurt most when rates rise",
      "Concentrated in technology at 55%+ of portfolio weight",
      "Valuation premium to the broad market requires continued earnings delivery",
    ],
    catalysts: [
      "AI monetization accelerating earnings per share at top holdings",
      "Multiple expansion if long-term rates normalize lower",
      "Continued innovation cycles extending competitive moats",
    ],
    expenseRatio: 0.04,
    aum: "$155B",
    holdings: 183,
  },
  {
    ticker: "VTV",
    name: "Vanguard Value ETF",
    sector: "Finance",
    type: "etf" as const,
    price: 168.42,
    change: 0.54,
    changePercent: 0.32,
    marketCap: "$125B",
    peRatio: 18.1,
    dividendYield: 2.37,
    fiftyTwoHigh: 178.97,
    fiftyTwoLow: 144.28,
    analystRating: "Buy",
    aiScore: 76,
    beta: 0.88,
    description: "Tracks US large-cap value stocks with low price-to-book and price-to-earnings ratios",
    thesis:
      "Value stocks trade at a historically wide discount to growth. Rising rates favor financials and energy, VTV's top sectors. Dividend income provides a return floor in flat or down markets.",
    risks: [
      "Value factor has underperformed growth for over a decade",
      "Heavy financials exposure creates rate and credit cycle sensitivity",
      "Slow earnings growth relative to technology sector",
    ],
    catalysts: [
      "Mean reversion from extreme growth-to-value valuation spread",
      "Financials benefiting from steeper yield curve",
      "Institutional rotation to defensive dividend payers in late cycle",
    ],
    expenseRatio: 0.04,
    aum: "$125B",
    holdings: 344,
  },
  {
    ticker: "SCHD",
    name: "Schwab US Dividend Equity ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 27.85,
    change: 0.12,
    changePercent: 0.43,
    marketCap: "$65B",
    peRatio: 17.4,
    dividendYield: 3.54,
    fiftyTwoHigh: 29.67,
    fiftyTwoLow: 23.49,
    analystRating: "Strong Buy",
    aiScore: 80,
    beta: 0.78,
    description: "Selects 100 US stocks with high dividend yield, strong fundamentals, and 10-year dividend growth history",
    thesis:
      "Best-in-class dividend ETF with a rigorous quality screen that filters for both yield and dividend sustainability. 0.06% expense ratio at Schwab. Consistent dividend growth creates an inflation-fighting income stream.",
    risks: [
      "Rising rates make dividend yields less attractive relative to fixed income",
      "Sector tilts away from high-growth technology reduces upside capture",
      "Dividend cuts during recessions can reduce income unexpectedly",
    ],
    catalysts: [
      "Investor rotation to income in late economic cycle",
      "Rate cuts increasing relative attractiveness of dividend yields",
      "Constituent companies with strong free cash flow growing dividends",
    ],
    expenseRatio: 0.06,
    aum: "$65B",
    holdings: 100,
  },
  {
    ticker: "VIG",
    name: "Vanguard Dividend Appreciation ETF",
    sector: "Broad Market",
    type: "etf" as const,
    price: 195.47,
    change: 0.83,
    changePercent: 0.43,
    marketCap: "$95B",
    peRatio: 23.5,
    dividendYield: 1.72,
    fiftyTwoHigh: 206.89,
    fiftyTwoLow: 166.23,
    analystRating: "Buy",
    aiScore: 79,
    beta: 0.82,
    description: "Tracks companies with 10+ consecutive years of dividend growth, emphasizing dividend sustainability",
    thesis:
      "Dividend growers outperform the broader market over full market cycles with lower drawdowns. The 10-year growth requirement filters for high-quality businesses with durable competitive advantages. Lower volatility than SPY.",
    risks: [
      "Lower current yield than SCHD limits appeal to income-focused investors",
      "Quality screen reduces universe to large established companies with limited upside",
      "Dividend growth can stall or reverse in severe recessions",
    ],
    catalysts: [
      "Quality factor premium in risk-off environments",
      "Dividend growers expanding payout ratios from strong earnings",
      "Defensive characteristics attractive as economic cycle matures",
    ],
    expenseRatio: 0.06,
    aum: "$95B",
    holdings: 289,
  },
  {
    ticker: "XLK",
    name: "Technology Select Sector SPDR Fund",
    sector: "Technology",
    type: "etf" as const,
    price: 226.14,
    change: 3.41,
    changePercent: 1.53,
    marketCap: "$72B",
    peRatio: 34.7,
    dividendYield: 0.64,
    fiftyTwoHigh: 255.60,
    fiftyTwoLow: 183.31,
    analystRating: "Buy",
    aiScore: 85,
    beta: 1.24,
    description: "Pure technology sector ETF holding S&P 500 tech stocks led by Apple, Nvidia, and Microsoft",
    thesis:
      "Direct exposure to the sector responsible for the majority of S&P 500 earnings growth. AI infrastructure spending benefits top three holdings simultaneously. Low 0.09% expense ratio for single-sector precision.",
    risks: [
      "Concentration risk -- Apple and Nvidia alone exceed 40% of fund weight",
      "Antitrust and regulatory actions targeting mega-cap tech",
      "High valuation multiples compress sharply if growth disappoints",
    ],
    catalysts: [
      "Nvidia data center revenue sustaining triple-digit growth",
      "Apple Intelligence feature set driving device upgrade cycle",
      "Enterprise AI software adoption expanding Microsoft Azure revenue",
    ],
    expenseRatio: 0.09,
    aum: "$72B",
    holdings: 67,
  },
  {
    ticker: "XLF",
    name: "Financial Select Sector SPDR Fund",
    sector: "Finance",
    type: "etf" as const,
    price: 48.73,
    change: 0.34,
    changePercent: 0.70,
    marketCap: "$48B",
    peRatio: 17.2,
    dividendYield: 1.53,
    fiftyTwoHigh: 53.04,
    fiftyTwoLow: 37.97,
    analystRating: "Buy",
    aiScore: 77,
    beta: 1.11,
    description: "S&P 500 financials sector ETF holding banks, insurers, asset managers, and payment networks",
    thesis:
      "Financial sector trades at compelling valuations relative to the market. Steeper yield curve improves net interest margins at banks. Deregulatory environment under current administration benefits M&A activity and capital returns.",
    risks: [
      "Credit quality deterioration if unemployment rises",
      "Inverted or flat yield curve compresses bank net interest margins",
      "Regulatory capital requirements could limit shareholder returns",
    ],
    catalysts: [
      "Yield curve steepening expanding bank profitability",
      "M&A wave from reduced regulatory friction boosting investment banking fees",
      "Loan growth recovery as businesses resume capital investment",
    ],
    expenseRatio: 0.09,
    aum: "$48B",
    holdings: 72,
  },
  {
    ticker: "XLE",
    name: "Energy Select Sector SPDR Fund",
    sector: "Energy",
    type: "etf" as const,
    price: 93.28,
    change: -0.61,
    changePercent: -0.65,
    marketCap: "$38B",
    peRatio: 14.1,
    dividendYield: 3.21,
    fiftyTwoHigh: 101.65,
    fiftyTwoLow: 78.43,
    analystRating: "Hold",
    aiScore: 72,
    beta: 0.97,
    description: "S&P 500 energy sector ETF dominated by ExxonMobil and Chevron with oil and gas exposure",
    thesis:
      "Energy sector generates strong free cash flow at current oil prices. Attractive dividend yield with ongoing buyback programs. Supply discipline from OPEC and reduced US drilling capex supports oil prices structurally.",
    risks: [
      "Oil price volatility from geopolitical supply disruptions or demand slowdowns",
      "Energy transition secular headwinds as EVs displace oil demand long term",
      "Concentration in two names -- Exxon and Chevron comprise 45%+ of the fund",
    ],
    catalysts: [
      "Sustained oil prices above $75 driving free cash flow and buybacks",
      "LNG export infrastructure buildout expanding gas revenue",
      "Geopolitical supply disruptions tightening global oil market",
    ],
    expenseRatio: 0.09,
    aum: "$38B",
    holdings: 23,
  },
  {
    ticker: "XLV",
    name: "Health Care Select Sector SPDR Fund",
    sector: "Healthcare",
    type: "etf" as const,
    price: 148.92,
    change: 0.47,
    changePercent: 0.32,
    marketCap: "$40B",
    peRatio: 21.3,
    dividendYield: 1.54,
    fiftyTwoHigh: 161.55,
    fiftyTwoLow: 127.21,
    analystRating: "Buy",
    aiScore: 78,
    beta: 0.66,
    description: "S&P 500 healthcare sector ETF covering pharma, biotech, medical devices, and managed care",
    thesis:
      "Defensive sector with inelastic demand growing alongside aging demographics. GLP-1 drug revolution at Eli Lilly creates sustained earnings growth. Medical devices and diagnostics benefit from post-pandemic procedure recovery.",
    risks: [
      "Drug pricing policy risk from Medicare negotiation expansion",
      "Patent cliffs at major pharma companies creating earnings gaps",
      "Biotech volatility from clinical trial failures affecting sector sentiment",
    ],
    catalysts: [
      "GLP-1 obesity drug adoption expanding total addressable markets",
      "Aging baby boomer cohort accelerating healthcare utilization",
      "AI drug discovery reducing R&D timelines and costs",
    ],
    expenseRatio: 0.09,
    aum: "$40B",
    holdings: 63,
  },
  {
    ticker: "VWO",
    name: "Vanguard FTSE Emerging Markets ETF",
    sector: "International",
    type: "etf" as const,
    price: 44.81,
    change: -0.23,
    changePercent: -0.51,
    marketCap: "$82B",
    peRatio: 13.6,
    dividendYield: 2.97,
    fiftyTwoHigh: 48.77,
    fiftyTwoLow: 37.50,
    analystRating: "Hold",
    aiScore: 70,
    beta: 0.84,
    description: "Tracks the FTSE Emerging Markets All Cap China A Inclusion Index across 24 countries",
    thesis:
      "Emerging markets trade at the widest valuation discount to US equities in two decades. China stimulus policy could trigger significant re-rating. Demographics and middle class growth in India and Southeast Asia drive long-run demand.",
    risks: [
      "China makes up 30%+ of the fund and faces geopolitical and regulatory uncertainty",
      "Strong US dollar is a structural headwind for dollar-denominated EM returns",
      "Political instability and capital controls in select EM economies",
    ],
    catalysts: [
      "China consumer stimulus triggering broad EM equity re-rating",
      "Indian equity market compounding as the world's fastest growing large economy",
      "US dollar weakening boosting local currency returns for US investors",
    ],
    expenseRatio: 0.08,
    aum: "$82B",
    holdings: 5858,
  },
  {
    ticker: "VXUS",
    name: "Vanguard Total International Stock ETF",
    sector: "International",
    type: "etf" as const,
    price: 61.34,
    change: -0.19,
    changePercent: -0.31,
    marketCap: "$75B",
    peRatio: 14.8,
    dividendYield: 3.11,
    fiftyTwoHigh: 67.47,
    fiftyTwoLow: 51.26,
    analystRating: "Hold",
    aiScore: 71,
    beta: 0.87,
    description: "Owns every non-US equity across developed and emerging markets in a single fund",
    thesis:
      "International equities offer compelling value at 14x earnings versus 25x for the S&P 500. Geographic diversification reduces dependence on any single economy. Paired with VTI, creates a complete global equity portfolio.",
    risks: [
      "US dollar strength erodes returns from foreign currency assets",
      "European economic stagnation weighs on developed market performance",
      "China exposure introduces geopolitical concentration risk",
    ],
    catalysts: [
      "Dollar cycle peak and reversal amplifying international equity returns",
      "Valuation mean reversion from extreme US-vs-world gap",
      "European fiscal stimulus packages reigniting growth",
    ],
    expenseRatio: 0.07,
    aum: "$75B",
    holdings: 8550,
  },
  {
    ticker: "BND",
    name: "Vanguard Total Bond Market ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 73.48,
    change: 0.11,
    changePercent: 0.15,
    marketCap: "$120B",
    peRatio: 0,
    dividendYield: 4.42,
    fiftyTwoHigh: 75.42,
    fiftyTwoLow: 70.87,
    analystRating: "Buy",
    aiScore: 75,
    beta: 0.04,
    description: "Tracks the Bloomberg US Aggregate Bond Index covering investment-grade US bonds",
    thesis:
      "Core fixed income exposure at 0.03% expense ratio. Provides portfolio ballast against equity market volatility. Near 4.4% yield is attractive relative to 10-year historical averages and beats cash once rates normalize lower.",
    risks: [
      "Duration risk -- rising rates push bond prices down",
      "Inflation reacceleration erodes real returns from fixed income",
      "Government debt expansion pressuring long-end yields higher",
    ],
    catalysts: [
      "Fed rate cut cycle beginning creates price appreciation from duration",
      "Flight to quality during equity market stress drives demand",
      "Yield lock-in at current levels attractive if rates decline",
    ],
    expenseRatio: 0.03,
    aum: "$120B",
    holdings: 17514,
  },
  {
    ticker: "AGG",
    name: "iShares Core US Aggregate Bond ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 96.71,
    change: 0.14,
    changePercent: 0.14,
    marketCap: "$108B",
    peRatio: 0,
    dividendYield: 4.38,
    fiftyTwoHigh: 99.04,
    fiftyTwoLow: 93.32,
    analystRating: "Buy",
    aiScore: 74,
    beta: 0.04,
    description: "iShares equivalent of BND tracking the Bloomberg US Aggregate Bond Index",
    thesis:
      "Institutional standard for US core fixed income. More widely used than BND in institutional portfolios, offering superior liquidity for large trades. Identical index exposure makes the choice between BND and AGG purely about cost and liquidity needs.",
    risks: [
      "Rate duration creates mark-to-market losses if yields rise further",
      "Government and agency bonds dominate -- limited credit yield pickup",
      "Inflation erodes purchasing power of fixed coupon payments",
    ],
    catalysts: [
      "Fed rate cuts boosting total return through price appreciation",
      "Recession fears increasing safe-haven demand for investment-grade bonds",
      "Corporate bond spread compression in improving credit environments",
    ],
    expenseRatio: 0.03,
    aum: "$108B",
    holdings: 11730,
  },
  {
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    sector: "Fixed Income",
    type: "etf" as const,
    price: 87.43,
    change: 0.62,
    changePercent: 0.71,
    marketCap: "$52B",
    peRatio: 0,
    dividendYield: 4.71,
    fiftyTwoHigh: 101.22,
    fiftyTwoLow: 82.42,
    analystRating: "Hold",
    aiScore: 70,
    beta: -0.22,
    description: "Tracks long-dated US Treasury bonds with maturities of 20 years or more",
    thesis:
      "Highest duration Treasury ETF offering maximum price appreciation in a falling rate environment. Negative beta provides genuine portfolio hedging versus equity drawdowns. Near 4.7% yield with government backing.",
    risks: [
      "Extreme duration -- each 1% rate rise causes approximately 17% price decline",
      "Fiscal deficit expansion could structurally keep long rates elevated",
      "Inflation regime shift from supply-side factors limiting Fed cut scope",
    ],
    catalysts: [
      "Recession or growth scare triggering aggressive Fed rate cuts",
      "Flight to safety bid in geopolitical or financial market crises",
      "Inflation returning to target enabling Fed to ease at long end",
    ],
    expenseRatio: 0.15,
    aum: "$52B",
    holdings: 41,
  },
  {
    ticker: "GLD",
    name: "SPDR Gold Shares",
    sector: "Broad Market",
    type: "etf" as const,
    price: 241.87,
    change: 1.43,
    changePercent: 0.59,
    marketCap: "$76B",
    peRatio: 0,
    dividendYield: 0,
    fiftyTwoHigh: 261.30,
    fiftyTwoLow: 181.60,
    analystRating: "Buy",
    aiScore: 77,
    beta: 0.09,
    description: "Physical gold bullion ETF where each share represents approximately 1/10th of an ounce of gold",
    thesis:
      "Gold at all-time highs driven by central bank accumulation, geopolitical demand, and dollar diversification. Functions as portfolio insurance against tail risks including inflation, currency debasement, and geopolitical crises. Central bank buying provides structural floor.",
    risks: [
      "No yield -- opportunity cost relative to 4%+ cash rates",
      "Strong dollar is historically a headwind for gold prices",
      "Gold price tied to real interest rates -- rising real yields pressure price",
    ],
    catalysts: [
      "Central bank gold purchases at multi-decade highs providing demand floor",
      "Dollar weakening and real rate declines as Fed eases",
      "Geopolitical risk premium as a safe-haven asset in unstable environment",
    ],
    expenseRatio: 0.4,
    aum: "$76B",
    holdings: 1,
  },
  {
    ticker: "ARKK",
    name: "ARK Innovation ETF",
    sector: "Technology",
    type: "etf" as const,
    price: 51.24,
    change: 0.89,
    changePercent: 1.77,
    marketCap: "$7B",
    peRatio: 68.2,
    dividendYield: 0,
    fiftyTwoHigh: 63.17,
    fiftyTwoLow: 37.08,
    analystRating: "Hold",
    aiScore: 71,
    beta: 1.58,
    description: "Actively managed ETF targeting disruptive innovation across AI, genomics, fintech, and space",
    thesis:
      "High-conviction concentrated bets on companies Cathie Wood believes will define the next decade. Invests early in platforms like Tesla, Coinbase, and UiPath before institutional consensus. High-risk exposure to exponential technology themes.",
    risks: [
      "Concentrated in speculative high-multiple companies with no current earnings",
      "High fee (0.75%) for active management that has underperformed passive since 2021",
      "Liquidity mismatch -- large redemptions force selling of illiquid positions at poor prices",
    ],
    catalysts: [
      "AI adoption acceleration validating portfolio company revenue models",
      "Rate cuts expanding multiples on long-duration growth assets",
      "Bitcoin and crypto rally lifting Coinbase and crypto-adjacent holdings",
    ],
    expenseRatio: 0.75,
    aum: "$7B",
    holdings: 29,
  },
];
