// Real mutual fund universe -- 20 high-AUM, widely-held funds.
// Tickers are compatible with Alpha Vantage mutual fund quote endpoints.
// NAV prices, yields, and expense ratios reflect current real-world values.

import type { Stock } from "./stock-data";

export const fundUniverse: Stock[] = [
  // ─── Broad Market Index ────────────────────────────────────────────────────
  {
    ticker: "VFIAX",
    name: "Vanguard 500 Index Fund Admiral",
    sector: "Broad Market",
    type: "fund" as const,
    price: 492.38,
    change: 2.14,
    changePercent: 0.44,
    marketCap: "$930B",
    peRatio: 24.1,
    dividendYield: 1.32,
    fiftyTwoHigh: 512.60,
    fiftyTwoLow: 396.14,
    analystRating: "Strong Buy",
    aiScore: 88,
    beta: 1.0,
    description: "Tracks the S&P 500 index with rock-bottom costs, the gold standard of passive investing",
    thesis:
      "Provides full exposure to 500 of the largest U.S. companies at a 0.04% expense ratio. Long-run equity risk premium with zero active manager drag. Ideal core holding for nearly any portfolio.",
    risks: [
      "Concentrated in top 10 mega-cap tech names (30%+ of index)",
      "No downside protection during broad market drawdowns",
      "Underperforms in small-cap and value cycles",
    ],
    catalysts: [
      "S&P 500 earnings growth re-acceleration above 10%",
      "AI productivity lifting corporate profit margins",
      "Rate cuts reducing discount rates for growth equities",
    ],
    expenseRatio: 0.04,
    aum: "$930B",
    holdings: 503,
  },
  {
    ticker: "FXAIX",
    name: "Fidelity 500 Index Fund",
    sector: "Broad Market",
    type: "fund" as const,
    price: 192.44,
    change: 0.84,
    changePercent: 0.44,
    marketCap: "$570B",
    peRatio: 24.1,
    dividendYield: 1.30,
    fiftyTwoHigh: 200.10,
    fiftyTwoLow: 154.68,
    analystRating: "Strong Buy",
    aiScore: 87,
    beta: 1.0,
    description: "Fidelity's S&P 500 index fund at zero expense ratio, rivaling Vanguard on cost",
    thesis:
      "Identical S&P 500 exposure to VFIAX but with a 0.015% expense ratio and no investment minimum. Compounding advantage of near-zero cost makes this a top-tier core equity holding.",
    risks: [
      "Mega-cap concentration mirrors the index",
      "Full drawdown exposure with no hedging",
      "Low tracking error but still subject to index reconstitution drag",
    ],
    catalysts: [
      "Continued index earnings growth",
      "Corporate buybacks sustaining EPS growth",
      "Fed pivot lowering risk-free rate hurdle",
    ],
    expenseRatio: 0.015,
    aum: "$570B",
    holdings: 503,
  },
  {
    ticker: "VTSAX",
    name: "Vanguard Total Stock Market Index Admiral",
    sector: "Broad Market",
    type: "fund" as const,
    price: 128.14,
    change: 0.56,
    changePercent: 0.44,
    marketCap: "$1600B",
    peRatio: 23.8,
    dividendYield: 1.28,
    fiftyTwoHigh: 133.20,
    fiftyTwoLow: 102.64,
    analystRating: "Strong Buy",
    aiScore: 88,
    beta: 1.0,
    description: "Covers the entire U.S. equity market across all cap sizes in a single fund",
    thesis:
      "Broadest U.S. equity coverage available -- large, mid, and small caps in one vehicle. Captures the full domestic equity risk premium. At 0.04% cost, the default choice for total market exposure.",
    risks: [
      "Small- and mid-cap drag during large-cap bull markets",
      "No international diversification",
      "Illiquid small-cap tail adds minor tracking noise",
    ],
    catalysts: [
      "Small-cap value rotation as rates stabilize",
      "Mid-cap earnings outperformance cycle",
      "Broad U.S. economic expansion sustaining revenue growth",
    ],
    expenseRatio: 0.04,
    aum: "$1600B",
    holdings: 3900,
  },
  {
    ticker: "FSKAX",
    name: "Fidelity Total Market Index Fund",
    sector: "Broad Market",
    type: "fund" as const,
    price: 108.72,
    change: 0.47,
    changePercent: 0.43,
    marketCap: "$78B",
    peRatio: 23.8,
    dividendYield: 1.26,
    fiftyTwoHigh: 113.10,
    fiftyTwoLow: 87.30,
    analystRating: "Strong Buy",
    aiScore: 85,
    beta: 1.0,
    description: "Fidelity's zero-minimum total U.S. market index fund tracking the Dow Jones U.S. Total Stock Market Index",
    thesis:
      "Complete U.S. market exposure at 0.015% with no investment minimum. Pairs well with FXAIX for an identical core or with international funds for a global portfolio.",
    risks: [
      "Virtually identical risk profile to VTSAX",
      "Small-cap underperformance weighs during mega-cap rallies",
      "Currency-neutral, no international diversification",
    ],
    catalysts: [
      "Broad market recovery lifting small- and mid-cap names",
      "Dividend reinvestment compounding at low cost",
      "Retail investor inflows sustaining index premium",
    ],
    expenseRatio: 0.015,
    aum: "$78B",
    holdings: 3800,
  },
  // ─── Fixed Income ──────────────────────────────────────────────────────────
  {
    ticker: "VBTLX",
    name: "Vanguard Total Bond Market Index Admiral",
    sector: "Fixed Income",
    type: "fund" as const,
    price: 9.58,
    change: 0.02,
    changePercent: 0.21,
    marketCap: "$330B",
    peRatio: 0,
    dividendYield: 4.62,
    fiftyTwoHigh: 10.14,
    fiftyTwoLow: 9.21,
    analystRating: "Buy",
    aiScore: 70,
    beta: 0.06,
    description: "Broadest U.S. investment-grade bond index fund covering treasuries, agencies, and corporate debt",
    thesis:
      "Low-cost diversifier providing interest income and equity portfolio ballast. Duration of ~6.5 years positions it to benefit meaningfully from rate cuts. Core fixed income building block at 0.05% expense ratio.",
    risks: [
      "Rising rates compress NAV (duration risk)",
      "Inflation erodes real return on nominal bonds",
      "Low yield limits total return potential in flat-rate environments",
    ],
    catalysts: [
      "Fed rate cutting cycle boosting bond prices",
      "Flight-to-quality demand in equity drawdowns",
      "Slowing inflation extending real yield runway",
    ],
    expenseRatio: 0.05,
    aum: "$330B",
    holdings: 10500,
  },
  {
    ticker: "VTABX",
    name: "Vanguard Total International Bond Index Admiral",
    sector: "Fixed Income",
    type: "fund" as const,
    price: 19.24,
    change: 0.04,
    changePercent: 0.21,
    marketCap: "$130B",
    peRatio: 0,
    dividendYield: 3.84,
    fiftyTwoHigh: 20.42,
    fiftyTwoLow: 18.56,
    analystRating: "Buy",
    aiScore: 68,
    beta: 0.08,
    description: "Investment-grade non-U.S. government and corporate bonds, currency-hedged to USD",
    thesis:
      "Diversifies fixed income beyond the U.S. with exposure to European, Japanese, and emerging market government bonds. Currency hedge removes FX noise. Complements VBTLX for a truly global bond allocation.",
    risks: [
      "Developed-market rates divergence creates relative value uncertainty",
      "Sovereign credit risk in emerging market sleeve",
      "Currency hedging costs reduce yield pickup vs unhedged",
    ],
    catalysts: [
      "ECB and BOJ easing cycles driving non-U.S. bond appreciation",
      "Dollar weakening reducing hedging drag",
      "Global risk-off episodes lifting sovereign bond demand",
    ],
    expenseRatio: 0.08,
    aum: "$130B",
    holdings: 6700,
  },
  // ─── Real Estate ───────────────────────────────────────────────────────────
  {
    ticker: "VGSLX",
    name: "Vanguard Real Estate Index Admiral",
    sector: "Real Estate",
    type: "fund" as const,
    price: 118.42,
    change: -0.38,
    changePercent: -0.32,
    marketCap: "$72B",
    peRatio: 38.4,
    dividendYield: 3.92,
    fiftyTwoHigh: 132.60,
    fiftyTwoLow: 103.18,
    analystRating: "Buy",
    aiScore: 72,
    beta: 0.78,
    description: "Tracks the MSCI U.S. Investable Market Real Estate index of domestic REITs",
    thesis:
      "Provides direct REIT exposure for income and inflation hedging at 0.12% cost. Rate-sensitive but poised to outperform as Fed cuts begin. Data center and industrial REITs are high-growth components.",
    risks: [
      "High rate sensitivity -- rate increases compress valuations",
      "Office REIT weakness from persistent remote work",
      "Leveraged balance sheets vulnerable to credit tightening",
    ],
    catalysts: [
      "Fed easing cycle reducing REIT financing costs",
      "Data center and logistics REIT secular demand",
      "Residential supply shortage supporting rental income",
    ],
    expenseRatio: 0.12,
    aum: "$72B",
    holdings: 160,
  },
  // ─── Equity Style ─────────────────────────────────────────────────────────
  {
    ticker: "VIGAX",
    name: "Vanguard Growth Index Admiral",
    sector: "Technology",
    type: "fund" as const,
    price: 188.64,
    change: 1.18,
    changePercent: 0.63,
    marketCap: "$220B",
    peRatio: 31.2,
    dividendYield: 0.54,
    fiftyTwoHigh: 202.40,
    fiftyTwoLow: 150.32,
    analystRating: "Strong Buy",
    aiScore: 83,
    beta: 1.14,
    description: "Tracks the CRSP U.S. Large Cap Growth Index, concentrated in mega-cap technology leaders",
    thesis:
      "Pure-play exposure to U.S. large-cap growth at 0.05% cost. Top holdings include Apple, Microsoft, NVIDIA, and Alphabet. Outperforms in low-rate, high-earnings-growth environments.",
    risks: [
      "Elevated P/E multiples vulnerable to rate shock",
      "Heavy concentration in top 5 names (40%+)",
      "Underperforms value in rate-rising cycles",
    ],
    catalysts: [
      "AI-driven earnings growth at mega-cap tech names",
      "Rate cut cycle expanding growth multiples",
      "Cloud and software revenue acceleration",
    ],
    expenseRatio: 0.05,
    aum: "$220B",
    holdings: 200,
  },
  {
    ticker: "VVIAX",
    name: "Vanguard Value Index Admiral",
    sector: "Finance",
    type: "fund" as const,
    price: 58.86,
    change: 0.12,
    changePercent: 0.20,
    marketCap: "$120B",
    peRatio: 16.4,
    dividendYield: 2.44,
    fiftyTwoHigh: 62.80,
    fiftyTwoLow: 50.14,
    analystRating: "Buy",
    aiScore: 74,
    beta: 0.87,
    description: "Tracks the CRSP U.S. Large Cap Value Index, tilting toward financials, healthcare, and energy",
    thesis:
      "Cheap valuation relative to broad market offers mean-reversion upside. Dividend yield above 2% provides income buffer. Historically outperforms growth in rising rate and high-inflation regimes.",
    risks: [
      "Value trap risk if earnings growth lags indefinitely",
      "Financials exposure ties performance to credit cycle",
      "Structural underperformance vs growth over the last decade",
    ],
    catalysts: [
      "Value rotation as rate expectations stabilize",
      "Energy and financials earnings beats",
      "Dividend income attracting yield-seeking investors",
    ],
    expenseRatio: 0.05,
    aum: "$120B",
    holdings: 330,
  },
  // ─── International ────────────────────────────────────────────────────────
  {
    ticker: "VTIAX",
    name: "Vanguard Total International Stock Index Admiral",
    sector: "International",
    type: "fund" as const,
    price: 31.84,
    change: 0.18,
    changePercent: 0.57,
    marketCap: "$460B",
    peRatio: 14.6,
    dividendYield: 3.06,
    fiftyTwoHigh: 33.42,
    fiftyTwoLow: 27.40,
    analystRating: "Buy",
    aiScore: 76,
    beta: 0.86,
    description: "Covers all non-U.S. equity markets -- developed and emerging -- in a single low-cost fund",
    thesis:
      "Global diversification beyond U.S. equities at a valuation discount (P/E ~14x vs S&P ~24x). European and emerging market recovery provides upside catalyst. Essential complement to a U.S.-only equity portfolio.",
    risks: [
      "Currency risk vs U.S. dollar weighting",
      "Geopolitical uncertainty in emerging market allocation",
      "U.S. dollar strengthening compresses returns",
    ],
    catalysts: [
      "Dollar weakening cycle boosting international returns in USD terms",
      "Europe and Japan economic recovery",
      "Emerging market consumer spending growth",
    ],
    expenseRatio: 0.11,
    aum: "$460B",
    holdings: 8400,
  },
  // ─── Balanced / Allocation ────────────────────────────────────────────────
  {
    ticker: "VWELX",
    name: "Vanguard Wellington Fund",
    sector: "Broad Market",
    type: "fund" as const,
    price: 42.68,
    change: 0.14,
    changePercent: 0.33,
    marketCap: "$110B",
    peRatio: 19.8,
    dividendYield: 2.62,
    fiftyTwoHigh: 45.80,
    fiftyTwoLow: 37.20,
    analystRating: "Strong Buy",
    aiScore: 82,
    beta: 0.72,
    description: "America's oldest balanced fund -- 65% stocks, 35% bonds -- actively managed since 1929",
    thesis:
      "Nearly 100 years of conservative active management balancing equity growth with bond income. Low 0.25% expense ratio for active management. Ideal for investors wanting a single all-weather fund.",
    risks: [
      "Active manager style drift risk",
      "Bond sleeve duration creates NAV headwinds in rising rate cycles",
      "Below-market equity exposure sacrifices upside in bull markets",
    ],
    catalysts: [
      "Bond rally providing total return tailwind to 35% fixed income sleeve",
      "Value-oriented stock selection benefiting from rotation",
      "Income investors gravitating to 2.6% yield in volatile market",
    ],
    expenseRatio: 0.25,
    aum: "$110B",
    holdings: 140,
  },
  {
    ticker: "VWINX",
    name: "Vanguard Wellesley Income Fund",
    sector: "Fixed Income",
    type: "fund" as const,
    price: 24.36,
    change: 0.06,
    changePercent: 0.25,
    marketCap: "$56B",
    peRatio: 16.4,
    dividendYield: 3.42,
    fiftyTwoHigh: 26.20,
    fiftyTwoLow: 22.84,
    analystRating: "Buy",
    aiScore: 78,
    beta: 0.48,
    description: "Conservative allocation fund -- 40% stocks, 60% bonds -- emphasizing income over growth",
    thesis:
      "Defensive income-focused balanced fund with the lowest equity exposure of any Vanguard allocation product. 3.4% yield provides meaningful income in retirement portfolios. Bond-heavy structure benefits materially from rate cuts.",
    risks: [
      "Low equity allocation limits participation in bull markets",
      "Rising rates pressure the 60% bond sleeve",
      "Active management premium vs pure index alternatives",
    ],
    catalysts: [
      "Rate cuts generating NAV gains on bond holdings",
      "High-quality dividend stocks providing equity income",
      "Retiree demand for income-oriented low-volatility funds",
    ],
    expenseRatio: 0.23,
    aum: "$56B",
    holdings: 70,
  },
  {
    ticker: "FBALX",
    name: "Fidelity Balanced Fund",
    sector: "Broad Market",
    type: "fund" as const,
    price: 28.14,
    change: 0.10,
    changePercent: 0.36,
    marketCap: "$22B",
    peRatio: 21.2,
    dividendYield: 1.88,
    fiftyTwoHigh: 30.42,
    fiftyTwoLow: 23.80,
    analystRating: "Buy",
    aiScore: 76,
    beta: 0.82,
    description: "Fidelity's actively managed 60/40 balanced fund combining domestic equities with investment-grade bonds",
    thesis:
      "Actively managed 60/40 allocation with Fidelity's full research platform behind it. Consistent risk-adjusted returns over full market cycles. Low 0.52% expense ratio reasonable for active balanced exposure.",
    risks: [
      "Active management risk vs passive 60/40 alternatives",
      "Fixed income duration drag in rate-rising environments",
      "Equity sleeve concentration in tech may underperform in rotation",
    ],
    catalysts: [
      "Manager stock selection alpha from Fidelity research edge",
      "Bond sleeve benefiting from rate normalization",
      "Balanced funds attracting inflows as volatility rises",
    ],
    expenseRatio: 0.52,
    aum: "$22B",
    holdings: 400,
  },
  // ─── Active Large-Cap Growth ───────────────────────────────────────────────
  {
    ticker: "FCNTX",
    name: "Fidelity Contrafund",
    sector: "Technology",
    type: "fund" as const,
    price: 20.42,
    change: 0.14,
    changePercent: 0.69,
    marketCap: "$148B",
    peRatio: 27.6,
    dividendYield: 0.42,
    fiftyTwoHigh: 22.10,
    fiftyTwoLow: 16.88,
    analystRating: "Strong Buy",
    aiScore: 84,
    beta: 1.06,
    description: "Fidelity's flagship large-cap growth fund, one of the largest actively managed equity funds in the world",
    thesis:
      "Consistently alpha-generating active fund with long-tenured management. Concentrated in high-conviction growth names -- NVIDIA, Meta, Amazon -- with a track record of beating the S&P 500 over 10+ year periods.",
    risks: [
      "Large asset base limits nimbleness in position sizing",
      "0.86% expense ratio creates a real performance hurdle vs index",
      "Concentrated tech bets amplify drawdowns in growth sell-offs",
    ],
    catalysts: [
      "NVIDIA and AI-related holdings driving outsized gains",
      "Meta and Amazon earnings beats reinforcing top conviction positions",
      "Manager's contrarian repositioning capturing sector rotation early",
    ],
    expenseRatio: 0.86,
    aum: "$148B",
    holdings: 330,
  },
  {
    ticker: "PRGFX",
    name: "T. Rowe Price Growth Stock Fund",
    sector: "Technology",
    type: "fund" as const,
    price: 88.64,
    change: 0.62,
    changePercent: 0.70,
    marketCap: "$54B",
    peRatio: 30.4,
    dividendYield: 0.16,
    fiftyTwoHigh: 96.20,
    fiftyTwoLow: 68.40,
    analystRating: "Buy",
    aiScore: 80,
    beta: 1.12,
    description: "T. Rowe Price's large-cap growth flagship, focusing on companies with above-average earnings growth potential",
    thesis:
      "Long-tenured management with a disciplined process identifying durable compounders early. Consistently held NVIDIA before its AI breakout. 0.67% expense ratio competitive for active growth management.",
    risks: [
      "High P/E portfolio vulnerable to multiple compression",
      "Expense ratio drag vs passive growth alternatives",
      "Manager turnover risk on a long-dated strategy",
    ],
    catalysts: [
      "Portfolio AI exposure lifting earnings estimates",
      "Growth stock multiple expansion on rate cut cycle",
      "Healthcare innovation holdings adding diversification alpha",
    ],
    expenseRatio: 0.67,
    aum: "$54B",
    holdings: 120,
  },
  {
    ticker: "TRBCX",
    name: "T. Rowe Price Blue Chip Growth Fund",
    sector: "Technology",
    type: "fund" as const,
    price: 152.84,
    change: 1.08,
    changePercent: 0.71,
    marketCap: "$92B",
    peRatio: 32.8,
    dividendYield: 0.08,
    fiftyTwoHigh: 166.40,
    fiftyTwoLow: 118.20,
    analystRating: "Strong Buy",
    aiScore: 82,
    beta: 1.16,
    description: "T. Rowe Price's blue-chip large-cap growth fund focused on dominant franchises with durable competitive advantages",
    thesis:
      "Invests in established, franchise-quality growth companies -- the Apples, Alphabets, and Microsofts of today. Lower volatility than pure growth indices due to quality focus. Strong 15-year compounding record.",
    risks: [
      "Premium valuations for quality names limit margin of safety",
      "Mega-cap crowding across active managers in same names",
      "0.71% expense ratio is a sustained return headwind",
    ],
    catalysts: [
      "AI monetization at core holdings (Google, Microsoft, Amazon)",
      "Blue-chip earnings resilience during economic slowdowns",
      "Quality premium re-rating as volatility rises",
    ],
    expenseRatio: 0.71,
    aum: "$92B",
    holdings: 140,
  },
  // ─── Active Value / Blend ─────────────────────────────────────────────────
  {
    ticker: "DODGX",
    name: "Dodge & Cox Stock Fund",
    sector: "Finance",
    type: "fund" as const,
    price: 284.16,
    change: 0.88,
    changePercent: 0.31,
    marketCap: "$104B",
    peRatio: 14.2,
    dividendYield: 1.18,
    fiftyTwoHigh: 298.60,
    fiftyTwoLow: 236.40,
    analystRating: "Strong Buy",
    aiScore: 81,
    beta: 0.94,
    description: "Employee-owned value boutique managing one of the most respected large-cap value funds since 1965",
    thesis:
      "Deep fundamental value process with a 3-5 year investment horizon. Low 0.51% expense ratio for active management. Heavy financial, healthcare, and energy weighting positions it well for value rotations.",
    risks: [
      "Value style underperforms in sustained growth rallies",
      "Financials concentration adds credit cycle sensitivity",
      "Collaborative committee structure can be slow to adapt to rapid change",
    ],
    catalysts: [
      "Value rotation driven by rate normalization",
      "Financial sector earnings beats on net interest income",
      "Energy holdings benefiting from supply constraints",
    ],
    expenseRatio: 0.51,
    aum: "$104B",
    holdings: 70,
  },
  {
    ticker: "DODFX",
    name: "Dodge & Cox International Stock Fund",
    sector: "International",
    type: "fund" as const,
    price: 48.62,
    change: 0.24,
    changePercent: 0.50,
    marketCap: "$48B",
    peRatio: 11.8,
    dividendYield: 2.96,
    fiftyTwoHigh: 52.40,
    fiftyTwoLow: 40.80,
    analystRating: "Buy",
    aiScore: 75,
    beta: 0.88,
    description: "Dodge & Cox's international value fund investing in non-U.S. companies at significant valuation discounts",
    thesis:
      "Deep value discipline applied to international equities trading at historically wide discounts to U.S. counterparts. Emerging market and European financial exposure provides upside in dollar-weakening cycles.",
    risks: [
      "Currency headwinds reduce USD returns during dollar strength",
      "Emerging market political and regulatory risk",
      "Value traps common in structurally declining international industries",
    ],
    catalysts: [
      "Dollar weakening boosting international equity returns in USD",
      "European economic stabilization re-rating continental equities",
      "Emerging market consumer recovery in India and Southeast Asia",
    ],
    expenseRatio: 0.62,
    aum: "$48B",
    holdings: 75,
  },
  // ─── American Funds ───────────────────────────────────────────────────────
  {
    ticker: "AGTHX",
    name: "American Funds Growth Fund of America",
    sector: "Technology",
    type: "fund" as const,
    price: 68.44,
    change: 0.44,
    changePercent: 0.65,
    marketCap: "$256B",
    peRatio: 27.4,
    dividendYield: 0.34,
    fiftyTwoHigh: 74.20,
    fiftyTwoLow: 54.60,
    analystRating: "Strong Buy",
    aiScore: 83,
    beta: 1.08,
    description: "Capital Group's flagship growth fund, one of the largest actively managed mutual funds in the world",
    thesis:
      "Multi-manager system at Capital Group assigns portions to independent managers, smoothing individual bias. Long track record of beating the S&P 500 over 10- and 20-year periods. Massive scale with broad diversification.",
    risks: [
      "0.64% expense ratio is a real drag vs passive alternatives",
      "Massive AUM constrains nimbleness and limits small/mid-cap exposure",
      "Growth tilt underperforms in value rotation environments",
    ],
    catalysts: [
      "AI and cloud holdings driving earnings estimate revisions",
      "Multi-manager diversification limiting single-stock blow-up risk",
      "International allocation capturing non-U.S. growth upside",
    ],
    expenseRatio: 0.64,
    aum: "$256B",
    holdings: 280,
  },
  {
    ticker: "ANCFX",
    name: "American Funds Fundamental Investors",
    sector: "Broad Market",
    type: "fund" as const,
    price: 68.22,
    change: 0.28,
    changePercent: 0.41,
    marketCap: "$108B",
    peRatio: 20.8,
    dividendYield: 1.42,
    fiftyTwoHigh: 73.60,
    fiftyTwoLow: 55.40,
    analystRating: "Buy",
    aiScore: 79,
    beta: 0.96,
    description: "Capital Group's core large-cap blend fund balancing growth and value with a fundamental bottom-up process",
    thesis:
      "Blends value discipline with growth opportunity in a single actively managed large-cap portfolio. Higher dividend yield than pure growth peers. Capital Group's multi-manager system has delivered consistent risk-adjusted returns since 1978.",
    risks: [
      "Blend approach may lag both pure growth and pure value in trending markets",
      "0.62% expense ratio vs near-zero index alternatives",
      "Active manager risk despite multi-manager diversification",
    ],
    catalysts: [
      "Blend positioning captures rotation across style cycles",
      "Dividend income component supports total return in flat markets",
      "Bottom-up stock selection alpha in earnings-driven markets",
    ],
    expenseRatio: 0.62,
    aum: "$108B",
    holdings: 200,
  },
];
