// Extended stock universe -- popular retail and institutional names missing from the base set.
// Imported and merged in stock-data.ts.

import type { Stock } from "./stock-data";

export const extendedStocks: Stock[] = [
  // ─── Technology ───────────────────────────────────────────────────────
  {
    ticker: "AMD",
    name: "Advanced Micro Devices",
    sector: "Technology",
    type: "stock" as const,
    price: 164.52,
    change: 2.88,
    changePercent: 1.78,
    marketCap: "$266B",
    peRatio: 48.7,
    dividendYield: 0,
    fiftyTwoHigh: 227.3,
    fiftyTwoLow: 120.83,
    analystRating: "Buy",
    aiScore: 79,
    beta: 1.68,
    description: "AI and data center chip challenger competing with NVIDIA and Intel",
    thesis:
      "AI accelerator business ramping with MI300X competing directly against NVIDIA. Data center GPU revenue tripling. CPU market share gains continue vs Intel.",
    risks: [
      "NVIDIA dominance in AI training market is entrenched",
      "Gross margins trail NVIDIA significantly",
      "Execution risk on AI product roadmap",
    ],
    catalysts: [
      "MI300X revenue ramp from hyperscaler adoption",
      "Server CPU market share approaching 30%",
      "Embedded and gaming segments recovery",
    ],
  },
  {
    ticker: "INTC",
    name: "Intel Corporation",
    sector: "Technology",
    type: "stock" as const,
    price: 24.18,
    change: -0.42,
    changePercent: -1.71,
    marketCap: "$104B",
    peRatio: 0,
    dividendYield: 2.08,
    fiftyTwoHigh: 42.95,
    fiftyTwoLow: 18.51,
    analystRating: "Hold",
    aiScore: 35,
    beta: 1.05,
    description: "Legacy chip giant pursuing foundry turnaround under new leadership",
    thesis:
      "Turnaround story under new leadership. Foundry ambitions with 18A process node. Government CHIPS Act subsidies provide cash runway but execution risks are significant.",
    risks: [
      "Massive capex burn on foundry buildout",
      "Continued market share loss to AMD and ARM-based chips",
      "No competitive AI accelerator product",
    ],
    catalysts: [
      "CHIPS Act funding unlocking fab investments",
      "18A process node attracting external foundry customers",
      "Cost restructuring improving margins",
    ],
  },
  {
    ticker: "ORCL",
    name: "Oracle Corporation",
    sector: "Technology",
    type: "stock" as const,
    price: 178.44,
    change: 1.56,
    changePercent: 0.88,
    marketCap: "$492B",
    peRatio: 36.8,
    dividendYield: 0.89,
    fiftyTwoHigh: 198.31,
    fiftyTwoLow: 112.88,
    analystRating: "Buy",
    aiScore: 74,
    beta: 1.08,
    description: "Enterprise database and cloud infrastructure provider attracting AI workloads",
    thesis:
      "Cloud infrastructure revenue growing 50%+ as Oracle Cloud attracts AI workloads. Database monopoly provides stable cash flow. Cerner healthcare integration expanding TAM.",
    risks: [
      "Cloud market share still tiny vs AWS, Azure, GCP",
      "Legacy on-premise revenue declining",
      "High debt from acquisitions",
    ],
    catalysts: [
      "Multi-cloud partnerships with AWS and Azure",
      "AI infrastructure demand filling data centers",
      "Healthcare IT cross-sell from Cerner",
    ],
  },
  {
    ticker: "IBM",
    name: "International Business Machines",
    sector: "Technology",
    type: "stock" as const,
    price: 231.85,
    change: 0.72,
    changePercent: 0.31,
    marketCap: "$213B",
    peRatio: 31.2,
    dividendYield: 2.86,
    fiftyTwoHigh: 264.87,
    fiftyTwoLow: 162.35,
    analystRating: "Hold",
    aiScore: 58,
    beta: 0.82,
    description: "Enterprise IT services and hybrid cloud company with WatsonX AI platform",
    thesis:
      "Hybrid cloud and AI consulting business stabilizing after years of decline. WatsonX AI platform targeting enterprise. Strong dividend provides income floor.",
    risks: [
      "Consulting revenue exposed to enterprise spending cycles",
      "AI strategy unproven vs hyperscaler offerings",
      "Legacy infrastructure segment still declining",
    ],
    catalysts: [
      "WatsonX enterprise AI adoption",
      "Red Hat hybrid cloud growth sustaining mid-teens",
      "Consulting bookings recovering",
    ],
  },
  {
    ticker: "CSCO",
    name: "Cisco Systems",
    sector: "Technology",
    type: "stock" as const,
    price: 58.92,
    change: 0.34,
    changePercent: 0.58,
    marketCap: "$237B",
    peRatio: 18.6,
    dividendYield: 2.68,
    fiftyTwoHigh: 62.88,
    fiftyTwoLow: 44.01,
    analystRating: "Hold",
    aiScore: 55,
    beta: 0.88,
    description: "Network infrastructure leader benefiting from AI data center buildout",
    thesis:
      "Network infrastructure leader benefiting from AI data center buildout. Splunk acquisition adding security and observability revenue. Transition to recurring software model progressing.",
    risks: [
      "Hardware refresh cycles create lumpy revenue",
      "Enterprise spending could slow in downturn",
      "Splunk integration execution risk",
    ],
    catalysts: [
      "AI-driven network upgrade cycle",
      "Security portfolio expansion via Splunk",
      "Recurring revenue mix approaching 50%",
    ],
  },
  {
    ticker: "QCOM",
    name: "Qualcomm",
    sector: "Technology",
    type: "stock" as const,
    price: 172.35,
    change: 1.92,
    changePercent: 1.13,
    marketCap: "$192B",
    peRatio: 19.4,
    dividendYield: 1.86,
    fiftyTwoHigh: 230.63,
    fiftyTwoLow: 142.81,
    analystRating: "Buy",
    aiScore: 68,
    beta: 1.35,
    description: "Mobile chip leader driving on-device AI in smartphones, PCs, and vehicles",
    thesis:
      "On-device AI driving premium smartphone upgrade cycle. Snapdragon X Elite competing in PC market. Automotive design wins providing multi-year revenue visibility.",
    risks: [
      "Apple building custom modem to replace Qualcomm",
      "China smartphone demand uncertainty",
      "PC chip market share unproven against Intel/AMD",
    ],
    catalysts: [
      "On-device AI features driving ASP increases",
      "Automotive revenue growing 30%+ annually",
      "Snapdragon X Elite PC chip traction",
    ],
  },
  {
    ticker: "TXN",
    name: "Texas Instruments",
    sector: "Technology",
    type: "stock" as const,
    price: 195.28,
    change: -0.68,
    changePercent: -0.35,
    marketCap: "$178B",
    peRatio: 35.4,
    dividendYield: 2.62,
    fiftyTwoHigh: 220.39,
    fiftyTwoLow: 155.46,
    analystRating: "Hold",
    aiScore: 62,
    beta: 0.95,
    description: "Analog semiconductor leader with 80,000+ products and wide moat",
    thesis:
      "Analog semiconductor leader with wide moat and 80,000+ products. Investing in 300mm fab capacity for long-term cost advantage. Consistent capital return program.",
    risks: [
      "Cyclical industry -- analog inventory correction ongoing",
      "Heavy capex on new fabs depressing near-term FCF",
      "Auto and industrial end markets slowing",
    ],
    catalysts: [
      "Analog inventory cycle bottoming",
      "300mm fab cost advantage widening margins long-term",
      "Auto electrification increasing content per vehicle",
    ],
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies",
    sector: "Technology",
    type: "stock" as const,
    price: 82.45,
    change: 3.21,
    changePercent: 4.05,
    marketCap: "$188B",
    peRatio: 288.0,
    dividendYield: 0,
    fiftyTwoHigh: 125.41,
    fiftyTwoLow: 20.33,
    analystRating: "Hold",
    aiScore: 71,
    beta: 1.85,
    description: "AI and data analytics platform for government and enterprise customers",
    thesis:
      "AI Platform (AIP) driving commercial revenue acceleration. Government contracts provide stable base. Unique positioning at intersection of AI and national security.",
    risks: [
      "Extreme valuation -- 60x+ forward revenue",
      "Government revenue concentration and contract timing",
      "Commercial growth needs to prove sustainability",
    ],
    catalysts: [
      "AIP bootcamps converting enterprise pilots to contracts",
      "US government AI spending acceleration",
      "S&P 500 inclusion driving institutional buying",
    ],
  },
  {
    ticker: "SHOP",
    name: "Shopify Inc.",
    sector: "Technology",
    type: "stock" as const,
    price: 108.72,
    change: 2.15,
    changePercent: 2.02,
    marketCap: "$140B",
    peRatio: 78.5,
    dividendYield: 0,
    fiftyTwoHigh: 129.38,
    fiftyTwoLow: 58.01,
    analystRating: "Buy",
    aiScore: 76,
    beta: 1.72,
    description: "E-commerce platform powering online stores for SMBs and enterprises",
    thesis:
      "E-commerce platform of choice for SMBs and increasingly enterprise. Merchant Solutions growing faster than Subscription. AI tools making it easier for merchants to sell.",
    risks: [
      "Amazon competitive pressure on merchant loyalty",
      "Consumer spending slowdown impacts merchant GMV",
      "Premium valuation requires sustained 25%+ growth",
    ],
    catalysts: [
      "Checkout market share gains via Shop Pay",
      "Enterprise push with Commerce Components",
      "AI-powered merchant tools driving adoption",
    ],
  },
  {
    ticker: "NOW",
    name: "ServiceNow",
    sector: "Technology",
    type: "stock" as const,
    price: 924.56,
    change: 8.34,
    changePercent: 0.91,
    marketCap: "$190B",
    peRatio: 64.2,
    dividendYield: 0,
    fiftyTwoHigh: 1057.57,
    fiftyTwoLow: 637.0,
    analystRating: "Strong Buy",
    aiScore: 85,
    beta: 1.15,
    description: "Enterprise workflow automation platform with near-monopoly in ITSM",
    thesis:
      "Enterprise workflow automation platform with near-monopoly in ITSM. AI agents and GenAI features driving upsell. 97%+ renewal rates show extreme stickiness.",
    risks: [
      "Premium valuation -- 15x+ forward revenue",
      "Enterprise spending cycles could slow bookings",
      "AI disruption risk from new entrants",
    ],
    catalysts: [
      "Now Assist AI features driving Pro Plus tier adoption",
      "Platform expansion beyond IT into HR, Finance, Legal",
      "Federal government digital transformation spend",
    ],
  },
  // ─── Finance ──────────────────────────────────────────────────────────
  {
    ticker: "BAC",
    name: "Bank of America",
    sector: "Finance",
    type: "stock" as const,
    price: 42.88,
    change: 0.56,
    changePercent: 1.32,
    marketCap: "$338B",
    peRatio: 14.8,
    dividendYield: 2.33,
    fiftyTwoHigh: 48.08,
    fiftyTwoLow: 32.38,
    analystRating: "Buy",
    aiScore: 65,
    beta: 1.42,
    description: "Largest US consumer bank with massive deposit base and digital platform",
    thesis:
      "Largest US consumer bank with massive deposit base. Net interest income benefiting from higher rates. Digital banking platform Erica with 2B+ interactions.",
    risks: [
      "Credit losses rising as consumer health weakens",
      "Rate cuts would compress net interest margins",
      "Commercial real estate exposure concerns",
    ],
    catalysts: [
      "Consumer spending resilience supporting fee income",
      "Investment banking recovery from depressed levels",
      "Continued share buyback program",
    ],
  },
  {
    ticker: "WFC",
    name: "Wells Fargo",
    sector: "Finance",
    type: "stock" as const,
    price: 68.45,
    change: 0.82,
    changePercent: 1.21,
    marketCap: "$232B",
    peRatio: 13.2,
    dividendYield: 2.34,
    fiftyTwoHigh: 81.46,
    fiftyTwoLow: 47.85,
    analystRating: "Buy",
    aiScore: 60,
    beta: 1.18,
    description: "Major US bank in turnaround mode with asset cap removal as catalyst",
    thesis:
      "Turnaround story with asset cap removal as catalyst. Aggressive cost-cutting improving efficiency ratio. Strong mortgage business benefits from rate normalization.",
    risks: [
      "Fed asset cap still limiting growth",
      "Legacy regulatory issues and consent orders",
      "Mortgage market sensitive to rate movements",
    ],
    catalysts: [
      "Potential asset cap removal in 2025-2026",
      "Efficiency improvements driving earnings growth",
      "Capital return acceleration post asset-cap lift",
    ],
  },
  {
    ticker: "C",
    name: "Citigroup",
    sector: "Finance",
    type: "stock" as const,
    price: 67.92,
    change: 0.44,
    changePercent: 0.65,
    marketCap: "$128B",
    peRatio: 11.8,
    dividendYield: 3.16,
    fiftyTwoHigh: 73.38,
    fiftyTwoLow: 46.82,
    analystRating: "Hold",
    aiScore: 52,
    beta: 1.45,
    description: "Global bank with unmatched international presence and deep value discount",
    thesis:
      "Deep value play on transformation under CEO Jane Fraser. Global presence unmatched. Services business (treasury, securities) is hidden gem generating consistent fees.",
    risks: [
      "Transformation execution risk is multi-year",
      "Emerging markets exposure adds volatility",
      "Regulatory penalties and compliance costs ongoing",
    ],
    catalysts: [
      "Simplification strategy divesting non-core businesses",
      "Services revenue growing double digits",
      "Stock trades at 60% of tangible book -- deep discount",
    ],
  },
  {
    ticker: "MS",
    name: "Morgan Stanley",
    sector: "Finance",
    type: "stock" as const,
    price: 108.34,
    change: 1.28,
    changePercent: 1.20,
    marketCap: "$176B",
    peRatio: 17.6,
    dividendYield: 3.14,
    fiftyTwoHigh: 128.12,
    fiftyTwoLow: 80.29,
    analystRating: "Buy",
    aiScore: 72,
    beta: 1.38,
    description: "Wealth management powerhouse with E*TRADE integration and trading expertise",
    thesis:
      "Wealth management transformation successful -- now 50%+ of revenue from recurring sources. E*TRADE integration adds massive retail client base. Capital-light model reduces volatility.",
    risks: [
      "Market downturn impacts AUM and advisory fees",
      "Investment banking cyclically depressed",
      "Wealth management competition intensifying",
    ],
    catalysts: [
      "AUM growth as markets recover",
      "Investment banking pipeline rebuilding",
      "Workplace channel from E*TRADE converting to full clients",
    ],
  },
  {
    ticker: "MA",
    name: "Mastercard",
    sector: "Finance",
    type: "stock" as const,
    price: 528.42,
    change: 4.12,
    changePercent: 0.79,
    marketCap: "$508B",
    peRatio: 37.8,
    dividendYield: 0.54,
    fiftyTwoHigh: 564.46,
    fiftyTwoLow: 416.72,
    analystRating: "Strong Buy",
    aiScore: 84,
    beta: 1.05,
    description: "Global payments duopoly with Visa processing cross-border transactions",
    thesis:
      "Duopoly with Visa in global payments. Cross-border travel recovery driving premium revenue. Value-added services (fraud, analytics, consulting) growing 20%+.",
    risks: [
      "Regulatory scrutiny on interchange fees globally",
      "Real-time payment systems bypassing card networks",
      "Premium valuation requires consistent execution",
    ],
    catalysts: [
      "Cross-border volumes exceeding pre-COVID levels",
      "B2B payments TAM still largely unpenetrated",
      "Value-added services becoming larger revenue driver",
    ],
  },
  {
    ticker: "AXP",
    name: "American Express",
    sector: "Finance",
    type: "stock" as const,
    price: 282.15,
    change: 2.56,
    changePercent: 0.92,
    marketCap: "$202B",
    peRatio: 20.4,
    dividendYield: 0.99,
    fiftyTwoHigh: 300.87,
    fiftyTwoLow: 208.25,
    analystRating: "Buy",
    aiScore: 74,
    beta: 1.15,
    description: "Premium card network with affluent customer base and closed-loop data advantage",
    thesis:
      "Premium brand with affluent customer base spending more per card. Gen Z and Millennial card acquisition accelerating. Closed-loop network gives unique data advantage.",
    risks: [
      "Premium customer base could cut spending in recession",
      "Credit losses normalizing from historic lows",
      "Competition from fintech and bank card rewards",
    ],
    catalysts: [
      "Millennial and Gen Z fastest-growing demographic",
      "International expansion of premium card products",
      "Travel and entertainment spending staying strong",
    ],
  },
  {
    ticker: "PYPL",
    name: "PayPal Holdings",
    sector: "Finance",
    type: "stock" as const,
    price: 72.84,
    change: 1.12,
    changePercent: 1.56,
    marketCap: "$74B",
    peRatio: 17.2,
    dividendYield: 0,
    fiftyTwoHigh: 93.66,
    fiftyTwoLow: 56.18,
    analystRating: "Hold",
    aiScore: 54,
    beta: 1.42,
    description: "Digital payments platform with 400M+ accounts and Venmo consumer app",
    thesis:
      "Turnaround under new CEO Alex Chriss. Venmo monetization improving. Unbranded processing (Braintree) gaining share but low margin. 400M+ accounts is massive distribution.",
    risks: [
      "Apple Pay and Google Pay eroding consumer wallet share",
      "Braintree growth is low-margin commodity processing",
      "Branded checkout losing share to alternatives",
    ],
    catalysts: [
      "New checkout experiences improving conversion rates",
      "Venmo monetization through debit card and pay-with-Venmo",
      "Advertising platform leveraging transaction data",
    ],
  },
  {
    ticker: "SQ",
    name: "Block Inc.",
    sector: "Finance",
    type: "stock" as const,
    price: 78.56,
    change: 1.84,
    changePercent: 2.40,
    marketCap: "$48B",
    peRatio: 52.8,
    dividendYield: 0,
    fiftyTwoHigh: 99.35,
    fiftyTwoLow: 55.48,
    analystRating: "Buy",
    aiScore: 61,
    beta: 1.78,
    description: "Dual ecosystem connecting Square merchants with Cash App consumers",
    thesis:
      "Dual ecosystem: Square (merchants) and Cash App (consumers) creating a closed loop. Cash App 55M+ monthly actives. BNPL via Afterpay integration ongoing.",
    risks: [
      "Bitcoin revenue inflates top line but low margin",
      "SMB merchant segment exposed to economic cycles",
      "Afterpay acquisition integration slower than expected",
    ],
    catalysts: [
      "Cash App lending and financial services expansion",
      "Square ecosystem adding larger merchants",
      "Profitability improvements from cost discipline",
    ],
  },
  {
    ticker: "COIN",
    name: "Coinbase Global",
    sector: "Finance",
    type: "stock" as const,
    price: 248.92,
    change: 8.45,
    changePercent: 3.51,
    marketCap: "$63B",
    peRatio: 38.4,
    dividendYield: 0,
    fiftyTwoHigh: 349.75,
    fiftyTwoLow: 114.51,
    analystRating: "Buy",
    aiScore: 66,
    beta: 2.25,
    description: "Only major US public crypto exchange with institutional custody services",
    thesis:
      "Only major US publicly traded crypto exchange. Regulatory clarity improving. Subscription and services revenue diversifying beyond volatile trading fees.",
    risks: [
      "Revenue highly correlated to crypto market cycles",
      "Regulatory uncertainty despite improving outlook",
      "Competition from decentralized exchanges and TradFi",
    ],
    catalysts: [
      "Bitcoin ETF driving institutional crypto adoption",
      "Base (L2) blockchain growing developer ecosystem",
      "USDC partnership with Circle generating stable yield",
    ],
  },
  // ─── Consumer ─────────────────────────────────────────────────────────
  {
    ticker: "NKE",
    name: "Nike Inc.",
    sector: "Consumer",
    type: "stock" as const,
    price: 78.34,
    change: -0.92,
    changePercent: -1.16,
    marketCap: "$118B",
    peRatio: 28.6,
    dividendYield: 1.84,
    fiftyTwoHigh: 112.09,
    fiftyTwoLow: 70.75,
    analystRating: "Hold",
    aiScore: 56,
    beta: 1.08,
    description: "Iconic global athletic brand executing DTC and wholesale strategy reset",
    thesis:
      "Iconic global brand executing DTC transformation. Nike Direct growing but wholesale channel disruption caused inventory issues. New CEO refocusing on sport and wholesale relationships.",
    risks: [
      "Brand heat declining vs competitors like On, Hoka, New Balance",
      "China recovery slower than expected",
      "DTC strategy overcorrection damaged wholesale relationships",
    ],
    catalysts: [
      "New CEO strategic reset restoring wholesale partnerships",
      "Innovation pipeline in running and performance categories",
      "2026 World Cup driving global football engagement",
    ],
  },
  {
    ticker: "SBUX",
    name: "Starbucks Corporation",
    sector: "Consumer",
    type: "stock" as const,
    price: 98.72,
    change: 0.64,
    changePercent: 0.65,
    marketCap: "$113B",
    peRatio: 28.4,
    dividendYield: 2.28,
    fiftyTwoHigh: 110.97,
    fiftyTwoLow: 71.55,
    analystRating: "Hold",
    aiScore: 59,
    beta: 0.85,
    description: "Global coffee chain with 38,000+ stores and 34M loyalty members",
    thesis:
      "Global coffee brand with 38,000+ stores. Turnaround under new CEO Brian Niccol focused on simplifying operations. Loyalty program (34M members) drives repeat purchases.",
    risks: [
      "Same-store sales declining as traffic falls",
      "China market intensely competitive with Luckin Coffee",
      "Labor costs and unionization pressures on margins",
    ],
    catalysts: [
      "New CEO operational improvements speeding service",
      "Menu innovation driving ticket growth",
      "Loyalty program expansion driving frequency",
    ],
  },
  {
    ticker: "MCD",
    name: "McDonald's Corporation",
    sector: "Consumer",
    type: "stock" as const,
    price: 298.45,
    change: 1.28,
    changePercent: 0.43,
    marketCap: "$214B",
    peRatio: 26.8,
    dividendYield: 2.19,
    fiftyTwoHigh: 316.84,
    fiftyTwoLow: 243.53,
    analystRating: "Buy",
    aiScore: 72,
    beta: 0.68,
    description: "Global QSR leader with franchise model generating predictable royalty income",
    thesis:
      "Global QSR leader with franchised business model generating predictable high-margin royalty income. Digital ordering now 40%+ of sales in top markets. Dividend aristocrat.",
    risks: [
      "Consumer trade-down at lower income levels",
      "International currency headwinds",
      "Food safety incidents impacting traffic",
    ],
    catalysts: [
      "Value menu driving traffic from price-sensitive consumers",
      "Digital and loyalty program driving order frequency",
      "New unit growth in international markets",
    ],
  },
  {
    ticker: "DIS",
    name: "The Walt Disney Company",
    sector: "Consumer",
    type: "stock" as const,
    price: 112.38,
    change: 1.56,
    changePercent: 1.41,
    marketCap: "$205B",
    peRatio: 38.2,
    dividendYield: 0.89,
    fiftyTwoHigh: 122.54,
    fiftyTwoLow: 83.91,
    analystRating: "Buy",
    aiScore: 68,
    beta: 1.22,
    description: "Entertainment conglomerate with irreplaceable IP, parks, and streaming",
    thesis:
      "Irreplaceable IP portfolio (Marvel, Star Wars, Pixar, Disney). Streaming turning profitable. Parks generating record revenue. ESPN digital transformation underway.",
    risks: [
      "Streaming subscriber growth plateauing",
      "Linear TV decline accelerating (ESPN, ABC)",
      "Content costs remain elevated",
    ],
    catalysts: [
      "Disney+ reaching sustained profitability",
      "ESPN flagship direct-to-consumer launch",
      "Parks expansion (Epic Universe competition aside) driving record attendance",
    ],
  },
  {
    ticker: "UBER",
    name: "Uber Technologies",
    sector: "Consumer",
    type: "stock" as const,
    price: 78.92,
    change: 1.24,
    changePercent: 1.60,
    marketCap: "$165B",
    peRatio: 32.4,
    dividendYield: 0,
    fiftyTwoHigh: 87.00,
    fiftyTwoLow: 54.85,
    analystRating: "Strong Buy",
    aiScore: 78,
    beta: 1.45,
    description: "Dominant ride-sharing and delivery platform with network effects moat",
    thesis:
      "Dominant ride-sharing and delivery platform with network effects. Advertising business scaling rapidly. Autonomous vehicle partnerships position Uber as platform layer.",
    risks: [
      "Autonomous vehicles could disintermediate Uber long-term",
      "Regulatory classification of drivers varies by market",
      "Delivery margins structurally lower than mobility",
    ],
    catalysts: [
      "Advertising revenue approaching $1B annual run rate",
      "Uber One membership driving cross-platform loyalty",
      "Autonomous vehicle partnerships (Waymo, others) making Uber the distribution layer",
    ],
  },
  {
    ticker: "ABNB",
    name: "Airbnb Inc.",
    sector: "Consumer",
    type: "stock" as const,
    price: 148.56,
    change: 2.08,
    changePercent: 1.42,
    marketCap: "$95B",
    peRatio: 34.8,
    dividendYield: 0,
    fiftyTwoHigh: 170.10,
    fiftyTwoLow: 110.4,
    analystRating: "Buy",
    aiScore: 73,
    beta: 1.52,
    description: "Short-term rental marketplace with asset-light model and 45%+ margins",
    thesis:
      "Category creator in short-term rentals with massive brand recognition. Asset-light marketplace model with 45%+ EBITDA margins. International expansion still early.",
    risks: [
      "Regulatory crackdowns on short-term rentals in major cities",
      "Travel demand normalization post-pandemic rebound",
      "Host supply quality inconsistency",
    ],
    catalysts: [
      "Experiences and services expanding TAM beyond lodging",
      "International markets (Asia, LatAm) driving growth",
      "AI-powered trip planning features increasing engagement",
    ],
  },
  {
    ticker: "LOW",
    name: "Lowe's Companies",
    sector: "Consumer",
    type: "stock" as const,
    price: 252.84,
    change: 1.42,
    changePercent: 0.56,
    marketCap: "$145B",
    peRatio: 19.8,
    dividendYield: 1.78,
    fiftyTwoHigh: 274.82,
    fiftyTwoLow: 206.14,
    analystRating: "Buy",
    aiScore: 64,
    beta: 1.02,
    description: "Second-largest home improvement retailer growing Pro customer segment",
    thesis:
      "Second-largest home improvement retailer benefiting from aging housing stock driving repair demand. Pro customer segment growing. Margin expansion from Total Home strategy.",
    risks: [
      "Housing market slowdown reducing project spending",
      "DIY consumer weakness in discretionary projects",
      "Competition from Home Depot in Pro segment",
    ],
    catalysts: [
      "Pro customer penetration increasing",
      "Housing stock aging driving non-discretionary repair",
      "Rate cuts eventually stimulating housing turnover",
    ],
  },
  {
    ticker: "TGT",
    name: "Target Corporation",
    sector: "Consumer",
    type: "stock" as const,
    price: 132.56,
    change: 0.88,
    changePercent: 0.67,
    marketCap: "$61B",
    peRatio: 15.2,
    dividendYield: 3.32,
    fiftyTwoHigh: 181.86,
    fiftyTwoLow: 120.21,
    analystRating: "Hold",
    aiScore: 52,
    beta: 0.92,
    description: "Differentiated mass retailer with strong private labels and same-day delivery",
    thesis:
      "Differentiated mass retailer with strong private labels and curated brand partnerships. Same-day delivery via Shipt. Attractive dividend yield for retail sector.",
    risks: [
      "Discretionary categories (apparel, home) under pressure",
      "Theft and shrink impacting margins",
      "Consumer trade-down to dollar stores and Walmart",
    ],
    catalysts: [
      "Private label growth improving margins",
      "Beauty category outperformance (Ulta partnership)",
      "Inventory discipline improving sell-through rates",
    ],
  },
  // ─── Healthcare ───────────────────────────────────────────────────────
  {
    ticker: "PFE",
    name: "Pfizer Inc.",
    sector: "Healthcare",
    type: "stock" as const,
    price: 26.84,
    change: 0.18,
    changePercent: 0.67,
    marketCap: "$152B",
    peRatio: 48.6,
    dividendYield: 6.22,
    fiftyTwoHigh: 31.54,
    fiftyTwoLow: 24.48,
    analystRating: "Hold",
    aiScore: 48,
    beta: 0.62,
    description: "Mega-cap pharma deploying COVID windfall into oncology via Seagen acquisition",
    thesis:
      "Mega-cap pharma with massive COVID cash windfall deployed into $43B Seagen oncology acquisition. Pipeline diversification into oncology, obesity, and rare disease. Highest dividend yield in pharma.",
    risks: [
      "COVID revenue collapsed from $37B peak to single digits",
      "Seagen integration and execution risk",
      "Patent cliff on key drugs (Ibrance, Eliquis) approaching",
    ],
    catalysts: [
      "Seagen oncology portfolio revenue ramp",
      "Obesity drug pipeline (oral GLP-1) if successful",
      "Cost restructuring saving $4B annually",
    ],
  },
  {
    ticker: "MRK",
    name: "Merck & Co.",
    sector: "Healthcare",
    type: "stock" as const,
    price: 108.92,
    change: -0.34,
    changePercent: -0.31,
    marketCap: "$276B",
    peRatio: 22.4,
    dividendYield: 2.84,
    fiftyTwoHigh: 134.63,
    fiftyTwoLow: 98.61,
    analystRating: "Buy",
    aiScore: 70,
    beta: 0.48,
    description: "Pharma giant behind Keytruda, the world's best-selling drug",
    thesis:
      "Keytruda is the best-selling drug globally ($25B+ revenue) with expanding indications. Strong vaccine business (Gardasil, PNEUMOVAX). Active M&A to build beyond Keytruda.",
    risks: [
      "Keytruda patent cliff in 2028 threatens 40%+ of revenue",
      "Pipeline must replace $25B+ Keytruda revenue",
      "China anti-corruption campaign impacting pharma sales",
    ],
    catalysts: [
      "Keytruda subcutaneous formulation extending lifecycle",
      "Oncology pipeline (favezelimab, patritumab) advancing",
      "Animal health (Bravecto) steady growth contributor",
    ],
  },
  {
    ticker: "TMO",
    name: "Thermo Fisher Scientific",
    sector: "Healthcare",
    type: "stock" as const,
    price: 548.72,
    change: 3.28,
    changePercent: 0.60,
    marketCap: "$210B",
    peRatio: 32.6,
    dividendYield: 0.26,
    fiftyTwoHigh: 623.12,
    fiftyTwoLow: 454.73,
    analystRating: "Buy",
    aiScore: 75,
    beta: 0.92,
    description: "Life sciences tools leader providing instruments and reagents to biotech",
    thesis:
      "Life sciences tools leader -- the picks and shovels of biotech. Diversified across instruments, reagents, and services. Acquisitive growth strategy with strong integration track record.",
    risks: [
      "Biotech funding downturn impacting capital equipment orders",
      "China anti-corruption campaign slowing sales",
      "Post-COVID destocking cycle in reagents",
    ],
    catalysts: [
      "Biotech funding recovery driving instrument demand",
      "Cell and gene therapy tools growing rapidly",
      "Recurring revenue from consumables and services",
    ],
  },
  // ─── Energy ───────────────────────────────────────────────────────────
  {
    ticker: "COP",
    name: "ConocoPhillips",
    sector: "Energy",
    type: "stock" as const,
    price: 112.45,
    change: 1.56,
    changePercent: 1.41,
    marketCap: "$135B",
    peRatio: 12.8,
    dividendYield: 2.84,
    fiftyTwoHigh: 130.34,
    fiftyTwoLow: 96.24,
    analystRating: "Buy",
    aiScore: 64,
    beta: 1.25,
    description: "Pure-play E&P with lowest cost of supply in the oil industry",
    thesis:
      "Pure-play E&P with lowest cost of supply in the industry. Marathon Oil acquisition adds low-decline assets. Disciplined capital allocation with 30%+ return of capital to shareholders.",
    risks: [
      "Oil price volatility directly impacts earnings",
      "Energy transition reducing long-term fossil fuel demand",
      "Marathon Oil integration execution",
    ],
    catalysts: [
      "Marathon Oil synergies lowering cost structure",
      "LNG export capacity additions",
      "Share buyback reducing share count 3-4% annually",
    ],
  },
  // ─── Industrial ───────────────────────────────────────────────────────
  {
    ticker: "GE",
    name: "GE Aerospace",
    sector: "Industrial",
    type: "stock" as const,
    price: 194.56,
    change: 2.34,
    changePercent: 1.22,
    marketCap: "$212B",
    peRatio: 38.2,
    dividendYield: 0.62,
    fiftyTwoHigh: 199.08,
    fiftyTwoLow: 124.37,
    analystRating: "Strong Buy",
    aiScore: 82,
    beta: 1.18,
    description: "Pure-play aerospace company dominant in jet engine aftermarket services",
    thesis:
      "Pure-play aerospace after spinning off GE Vernova. Dominant in jet engine aftermarket services (LEAP, GEnx). Multi-decade installed base creates recurring revenue. Defense segment benefiting from global rearmament.",
    risks: [
      "Supply chain constraints limiting engine deliveries",
      "Quality issues (LEAP engine inspections) creating costs",
      "Cyclical exposure to airline capital spending",
    ],
    catalysts: [
      "Aftermarket services revenue growing 20%+ on flight hour recovery",
      "LEAP engine installed base tripling over next decade",
      "Defense budget increases driving military engine orders",
    ],
  },
  {
    ticker: "LMT",
    name: "Lockheed Martin",
    sector: "Industrial",
    type: "stock" as const,
    price: 478.92,
    change: 3.12,
    changePercent: 0.66,
    marketCap: "$114B",
    peRatio: 17.8,
    dividendYield: 2.62,
    fiftyTwoHigh: 618.95,
    fiftyTwoLow: 413.92,
    analystRating: "Buy",
    aiScore: 70,
    beta: 0.68,
    description: "Largest US defense contractor with F-35, missiles, and space systems",
    thesis:
      "Largest US defense contractor with F-35, missile defense, and space systems. Geopolitical tensions driving global defense spending increases. Massive backlog provides multi-year revenue visibility.",
    risks: [
      "F-35 production and sustainment cost overruns",
      "US defense budget uncertainty in deficit reduction scenarios",
      "Supply chain delays impacting delivery schedules",
    ],
    catalysts: [
      "NATO countries increasing defense spending to 2%+ GDP",
      "F-35 international orders accelerating",
      "Hypersonic weapons and space programs growing rapidly",
    ],
  },
  {
    ticker: "UPS",
    name: "United Parcel Service",
    sector: "Industrial",
    type: "stock" as const,
    price: 134.28,
    change: 0.92,
    changePercent: 0.69,
    marketCap: "$116B",
    peRatio: 21.4,
    dividendYield: 4.82,
    fiftyTwoHigh: 152.93,
    fiftyTwoLow: 123.12,
    analystRating: "Hold",
    aiScore: 55,
    beta: 0.92,
    description: "Global logistics leader with dense US delivery network and healthcare focus",
    thesis:
      "Global logistics leader with dense US delivery network. Healthcare logistics growing rapidly. Highest dividend yield in industrials. New labor contract removes overhang.",
    risks: [
      "E-commerce volume growth slowing post-pandemic",
      "Amazon building out competing delivery network",
      "Higher labor costs from new Teamsters contract",
    ],
    catalysts: [
      "Healthcare and specialty logistics higher margin growth",
      "Network automation reducing cost per package",
      "SMB market share gains via Digital Access Program",
    ],
  },
  {
    ticker: "FDX",
    name: "FedEx Corporation",
    sector: "Industrial",
    type: "stock" as const,
    price: 278.92,
    change: 2.14,
    changePercent: 0.77,
    marketCap: "$68B",
    peRatio: 16.8,
    dividendYield: 1.88,
    fiftyTwoHigh: 313.84,
    fiftyTwoLow: 224.69,
    analystRating: "Buy",
    aiScore: 63,
    beta: 1.15,
    description: "Express delivery and freight company consolidating networks for margin expansion",
    thesis:
      "Network consolidation from DRIVE program merging Ground and Express into unified system. Cost savings of $4B creating margin expansion. Freight spin-off simplifying business.",
    risks: [
      "Execution risk on massive network consolidation",
      "Global trade slowdown impacting international volumes",
      "Amazon diverting volume to own delivery network",
    ],
    catalysts: [
      "DRIVE cost savings flowing through to margins",
      "Freight business spin-off unlocking value",
      "E-commerce returns logistics opportunity",
    ],
  },
  // ─── Consumer (Auto / EV) ─────────────────────────────────────────────
  {
    ticker: "F",
    name: "Ford Motor Company",
    sector: "Consumer",
    type: "stock" as const,
    price: 10.84,
    change: 0.12,
    changePercent: 1.12,
    marketCap: "$43B",
    peRatio: 12.2,
    dividendYield: 5.54,
    fiftyTwoHigh: 14.85,
    fiftyTwoLow: 9.49,
    analystRating: "Hold",
    aiScore: 44,
    beta: 1.32,
    description: "Iconic automaker with strong truck franchise and Ford Pro commercial business",
    thesis:
      "Iconic American automaker with strong truck franchise (F-150). EV strategy being right-sized after massive losses. Ford Pro (commercial fleet) is the hidden value driver with 15%+ margins.",
    risks: [
      "EV segment losing billions annually",
      "Legacy ICE business facing margin pressure from competition",
      "UAW labor costs permanently higher",
    ],
    catalysts: [
      "Ford Pro commercial business growing double digits",
      "EV loss reduction from scaling back unprofitable models",
      "Hybrid lineup gaining share as EV demand normalizes",
    ],
  },
  {
    ticker: "GM",
    name: "General Motors",
    sector: "Consumer",
    type: "stock" as const,
    price: 48.56,
    change: 0.68,
    changePercent: 1.42,
    marketCap: "$56B",
    peRatio: 5.8,
    dividendYield: 0.99,
    fiftyTwoHigh: 58.35,
    fiftyTwoLow: 33.44,
    analystRating: "Buy",
    aiScore: 62,
    beta: 1.28,
    description: "Value-priced automaker scaling Ultium EV platform with strong truck mix",
    thesis:
      "Trades at lowest PE in auto industry despite strong execution. Ultium EV platform scaling. Cruise autonomous division restructured. GM Financial provides captive lending profit.",
    risks: [
      "Cyclical auto industry exposed to recession",
      "EV transition costs remain elevated",
      "China JV profitability deteriorating",
    ],
    catalysts: [
      "EV profitability improving as Ultium scales",
      "Truck and SUV mix supporting strong ASPs",
      "Massive share buyback program reducing float",
    ],
  },
  {
    ticker: "RIVN",
    name: "Rivian Automotive",
    sector: "Consumer",
    type: "stock" as const,
    price: 14.28,
    change: 0.56,
    changePercent: 4.08,
    marketCap: "$16B",
    peRatio: 0,
    dividendYield: 0,
    fiftyTwoHigh: 28.06,
    fiftyTwoLow: 8.26,
    analystRating: "Hold",
    aiScore: 42,
    beta: 2.15,
    description: "Premium EV truck startup with Amazon delivery van contract and VW partnership",
    thesis:
      "Premium EV truck maker with strong brand and Amazon delivery van contract. R2 platform (smaller, cheaper) targeting mass market. VW joint venture provides capital and technology.",
    risks: [
      "Cash burn rate remains high -- needs capital raises",
      "Production scaling challenges at Normal, IL plant",
      "Competition intensifying from legacy automakers",
    ],
    catalysts: [
      "R2 platform launch expanding addressable market",
      "VW joint venture injecting $5B capital",
      "Gross margin turning positive as production scales",
    ],
  },
  // ─── Communication Services ───────────────────────────────────────────
  {
    ticker: "SPOT",
    name: "Spotify Technology",
    sector: "Technology",
    type: "stock" as const,
    price: 584.32,
    change: 8.92,
    changePercent: 1.55,
    marketCap: "$116B",
    peRatio: 88.4,
    dividendYield: 0,
    fiftyTwoHigh: 652.98,
    fiftyTwoLow: 280.42,
    analystRating: "Buy",
    aiScore: 75,
    beta: 1.55,
    description: "Dominant audio streaming platform with 640M+ users across music and podcasts",
    thesis:
      "Dominant audio streaming platform with 640M+ users. Podcast and audiobook investments creating platform stickiness. Finally achieving sustainable profitability after years of losses.",
    risks: [
      "Music label licensing costs remain high (65%+ of revenue)",
      "Podcast monetization still unproven at scale",
      "Premium valuation requires sustained subscriber growth",
    ],
    catalysts: [
      "Price increases driving ARPU growth",
      "Audiobooks creating new engagement and revenue",
      "Gross margin expansion from podcasts and marketplace model",
    ],
  },
  // ─── Materials ────────────────────────────────────────────────────────
  {
    ticker: "LIN",
    name: "Linde plc",
    sector: "Industrial",
    type: "stock" as const,
    price: 468.92,
    change: 2.14,
    changePercent: 0.46,
    marketCap: "$225B",
    peRatio: 32.8,
    dividendYield: 1.18,
    fiftyTwoHigh: 488.32,
    fiftyTwoLow: 390.57,
    analystRating: "Buy",
    aiScore: 76,
    beta: 0.82,
    description: "Largest industrial gas company with recession-resistant take-or-pay contracts",
    thesis:
      "Largest industrial gas company globally. Essential supplier to every major industry. Long-term take-or-pay contracts provide recession-resistant revenue. Clean hydrogen positioned for energy transition.",
    risks: [
      "Industrial production slowdown impacts volumes",
      "Capital-intensive business model",
      "Hydrogen economy development slower than expected",
    ],
    catalysts: [
      "Clean hydrogen projects winning government subsidies",
      "Semiconductor fab expansions requiring ultra-pure gases",
      "Healthcare oxygen demand structurally growing",
    ],
  },
  {
    ticker: "PANW",
    name: "Palo Alto Networks",
    sector: "Technology",
    type: "stock" as const,
    price: 188.42,
    change: 3.56,
    changePercent: 1.93,
    marketCap: "$62B",
    peRatio: 48.6,
    dividendYield: 0,
    fiftyTwoHigh: 208.38,
    fiftyTwoLow: 140.75,
    analystRating: "Strong Buy",
    aiScore: 80,
    beta: 1.32,
    description: "Cybersecurity platform leader consolidating firewall, cloud, and SOC products",
    thesis:
      "Leading cybersecurity platform consolidating firewall, cloud, and SOC. Platformization strategy driving multi-product adoption. AI-driven security operations reducing analyst workload.",
    risks: [
      "Platformization transition temporarily slowing billings growth",
      "Crowdstrike and Zscaler competing for platform deals",
      "Free trial conversions from platformization uncertain",
    ],
    catalysts: [
      "Platformization deals driving large contract wins",
      "XSIAM AI-driven SOC replacing legacy SIEMs",
      "Remaining performance obligations growing 20%+",
    ],
  },
  {
    ticker: "SNOW",
    name: "Snowflake Inc.",
    sector: "Technology",
    type: "stock" as const,
    price: 172.84,
    change: 4.28,
    changePercent: 2.54,
    marketCap: "$58B",
    peRatio: 0,
    dividendYield: 0,
    fiftyTwoHigh: 237.72,
    fiftyTwoLow: 107.13,
    analystRating: "Buy",
    aiScore: 72,
    beta: 1.65,
    description: "Cloud data platform enabling AI and analytics workloads on unified data",
    thesis:
      "Cloud data platform enabling AI/ML workloads on unified data. Consumption model means revenue grows with customer data volumes. Data sharing and marketplace creating network effects.",
    risks: [
      "Consumption model means revenue can decline if usage drops",
      "Databricks competing aggressively in data lakehouse",
      "Not yet profitable on a GAAP basis",
    ],
    catalysts: [
      "Cortex AI features driving new workload adoption",
      "Large enterprise customers expanding data volume",
      "Government sector FedRAMP authorization driving public sector growth",
    ],
  },
  // ─── Technology (EDA / Networking) ────────────────────────────────────
  {
    ticker: "SNPS",
    name: "Synopsys Inc.",
    sector: "Technology",
    type: "stock" as const,
    price: 488.32,
    change: 3.64,
    changePercent: 0.75,
    marketCap: "$74B",
    peRatio: 38.4,
    dividendYield: 0,
    fiftyTwoHigh: 614.22,
    fiftyTwoLow: 421.47,
    analystRating: "Buy",
    aiScore: 78,
    beta: 1.12,
    description: "EDA software leader providing chip design tools to every major semiconductor company",
    thesis:
      "Dominant EDA duopoly with Cadence. Every advanced chip designed with Synopsys tools -- NVIDIA, Apple, AMD all depend on their software. AI chip design complexity driving higher tool spend. Ansys acquisition expands into simulation.",
    risks: [
      "Ansys acquisition integration and antitrust review risk",
      "China export restrictions limiting EDA software revenue",
      "High valuation leaves little margin for execution misses",
    ],
    catalysts: [
      "AI chip design requiring increasingly complex EDA workflows",
      "Ansys acquisition doubling TAM into simulation software",
      "Silicon lifecycle management growing recurring revenue",
    ],
  },
  {
    ticker: "CDNS",
    name: "Cadence Design Systems",
    sector: "Technology",
    type: "stock" as const,
    price: 312.56,
    change: 2.18,
    changePercent: 0.70,
    marketCap: "$85B",
    peRatio: 64.2,
    dividendYield: 0,
    fiftyTwoHigh: 339.42,
    fiftyTwoLow: 234.84,
    analystRating: "Buy",
    aiScore: 80,
    beta: 1.18,
    description: "EDA and IP software company powering chip design for the AI era",
    thesis:
      "EDA software duopoly partner to Synopsys. AI-driven chip design complexity increasing tool spend per customer. Palladium emulation systems seeing record demand from hyperscalers building custom silicon.",
    risks: [
      "EDA market is a duopoly -- limited competitive differentiation",
      "China revenue exposed to escalating export controls",
      "High PE requires consistent double-digit growth",
    ],
    catalysts: [
      "Hyperscaler custom silicon programs (Google TPU, Amazon Trainium) driving emulation demand",
      "Cerebrus AI-driven chip design tool achieving faster tape-outs",
      "System Design Enablement expanding into PCB and system-level design",
    ],
  },
  {
    ticker: "ANET",
    name: "Arista Networks",
    sector: "Technology",
    type: "stock" as const,
    price: 368.84,
    change: 5.12,
    changePercent: 1.41,
    marketCap: "$116B",
    peRatio: 48.6,
    dividendYield: 0,
    fiftyTwoHigh: 421.32,
    fiftyTwoLow: 242.34,
    analystRating: "Strong Buy",
    aiScore: 84,
    beta: 1.28,
    description: "Cloud networking company capturing AI data center buildout with 400G and 800G switches",
    thesis:
      "Cloud networking leader whose high-speed switching fabric is essential for AI GPU clusters. Microsoft and Meta are top customers building AI infrastructure at scale. Software-driven EOS platform creates sticky recurring revenue.",
    risks: [
      "Revenue concentration in Microsoft and Meta (40%+ of revenue)",
      "Cisco and Juniper competing in enterprise networking",
      "Supply chain constraints limiting high-speed switch shipments",
    ],
    catalysts: [
      "800G switch cycle driven by AI GPU cluster networking",
      "Campus networking expansion into enterprise verticals",
      "AI networking software revenue growing faster than hardware",
    ],
  },
  // ─── Finance (Data / Analytics) ───────────────────────────────────────
  {
    ticker: "SPGI",
    name: "S&P Global Inc.",
    sector: "Finance",
    type: "stock" as const,
    price: 488.72,
    change: 2.84,
    changePercent: 0.58,
    marketCap: "$158B",
    peRatio: 42.8,
    dividendYield: 0.78,
    fiftyTwoHigh: 528.88,
    fiftyTwoLow: 406.24,
    analystRating: "Buy",
    aiScore: 80,
    beta: 0.88,
    description: "Financial data and analytics company with dominant credit rating and index businesses",
    thesis:
      "Irreplaceable financial infrastructure -- credit ratings and market indices. Debt issuance cycles drive Ratings revenue. IHS Markit merger creating data and analytics powerhouse. Dividend aristocrat with 50+ years of increases.",
    risks: [
      "Debt issuance slowdown reducing Ratings revenue",
      "IHS Markit integration complexity",
      "Regulatory scrutiny of credit rating oligopoly",
    ],
    catalysts: [
      "Corporate debt refinancing wave driving Ratings revenue",
      "Private credit market growth expanding rating volumes",
      "Commodity Insights segment growing from energy transition data",
    ],
  },
  {
    ticker: "MCO",
    name: "Moody's Corporation",
    sector: "Finance",
    type: "stock" as const,
    price: 462.18,
    change: 3.12,
    changePercent: 0.68,
    marketCap: "$85B",
    peRatio: 44.6,
    dividendYield: 0.72,
    fiftyTwoHigh: 502.34,
    fiftyTwoLow: 366.48,
    analystRating: "Buy",
    aiScore: 78,
    beta: 0.92,
    description: "Credit rating and financial risk analytics company with near-duopoly market position",
    thesis:
      "Near-duopoly in credit ratings with S&P Global. Moody's Analytics (risk software and data) growing 10%+ annually and reducing cyclicality. Debt issuance essential function creating mandatory demand for ratings.",
    risks: [
      "Interest rate environment reduces corporate debt issuance",
      "Dodd-Frank regulatory changes could mandate rating competition",
      "Structured finance ratings carry reputational risk from 2008 history",
    ],
    catalysts: [
      "Private credit market growth requiring rating services",
      "Moody's Analytics ESG and climate risk products expanding TAM",
      "Emerging market debt issuance growth internationally",
    ],
  },
  // ─── Consumer (LatAm E-Commerce / Restaurants) ────────────────────────
  {
    ticker: "MELI",
    name: "MercadoLibre Inc.",
    sector: "Consumer",
    type: "stock" as const,
    price: 2148.56,
    change: 24.72,
    changePercent: 1.16,
    marketCap: "$108B",
    peRatio: 62.4,
    dividendYield: 0,
    fiftyTwoHigh: 2334.78,
    fiftyTwoLow: 1369.37,
    analystRating: "Strong Buy",
    aiScore: 86,
    beta: 1.52,
    description: "Dominant Latin American e-commerce and fintech platform across 18 countries",
    thesis:
      "Amazon and PayPal of Latin America combined in one company. E-commerce penetration in Brazil and Mexico still early innings. Mercado Pago fintech serving 50M+ users who lack traditional banking. Logistics network building flywheel effects.",
    risks: [
      "Currency devaluation in Argentina and Brazil compresses USD reported revenue",
      "Regulatory risk across 18 different country jurisdictions",
      "Competition from Amazon and Sea Limited expanding in LatAm",
    ],
    catalysts: [
      "Fintech credit portfolio growing as underbanked users build credit history",
      "Advertising revenue scaling on 400M+ annual buyers",
      "Mexico logistics buildout creating same-day delivery advantage",
    ],
  },
  {
    ticker: "CMG",
    name: "Chipotle Mexican Grill",
    sector: "Consumer",
    type: "stock" as const,
    price: 56.84,
    change: 0.48,
    changePercent: 0.85,
    marketCap: "$156B",
    peRatio: 52.8,
    dividendYield: 0,
    fiftyTwoHigh: 69.26,
    fiftyTwoLow: 47.93,
    analystRating: "Buy",
    aiScore: 77,
    beta: 1.02,
    description: "Fast casual restaurant chain growing unit count and digital ordering with industry-leading margins",
    thesis:
      "Best-in-class fast casual restaurant with 27%+ restaurant-level margins -- highest in QSR. Digital ordering at 35%+ of sales reduces labor cost per transaction. International expansion still early (Europe, Canada, Middle East).",
    risks: [
      "Consumer spending fatigue at premium price points",
      "Food safety incidents create immediate traffic declines",
      "New unit growth requires real estate in competitive markets",
    ],
    catalysts: [
      "Chipotlane drive-thru format enabling suburban and smaller market expansion",
      "International unit growth accelerating in Europe and Middle East",
      "Menu innovation (new proteins) driving check growth",
    ],
  },
  // ─── Healthcare (Devices / Biotech) ───────────────────────────────────
  {
    ticker: "ZTS",
    name: "Zoetis Inc.",
    sector: "Healthcare",
    type: "stock" as const,
    price: 162.48,
    change: 1.12,
    changePercent: 0.69,
    marketCap: "$74B",
    peRatio: 32.6,
    dividendYield: 1.18,
    fiftyTwoHigh: 198.24,
    fiftyTwoLow: 148.37,
    analystRating: "Buy",
    aiScore: 73,
    beta: 0.72,
    description: "Largest animal health company globally with companion animal drugs and diagnostics",
    thesis:
      "Largest animal health company globally with durable pet humanization tailwind. Librela and Solensia pain drugs for dogs and cats creating new blockbuster category. Companion animal portfolio growing double digits with pricing power.",
    risks: [
      "Companion animal spending discretionary in economic downturns",
      "Librela and Solensia safety signal monitoring ongoing",
      "Competition from Elanco and Boehringer Ingelheim in key categories",
    ],
    catalysts: [
      "Librela dog pain drug ramp toward $1B+ revenue",
      "Diagnostics segment growing from vet clinic instrument placements",
      "International markets adopting companion animal care culture",
    ],
  },
  {
    ticker: "REGN",
    name: "Regeneron Pharmaceuticals",
    sector: "Healthcare",
    type: "stock" as const,
    price: 712.84,
    change: -4.28,
    changePercent: -0.60,
    marketCap: "$76B",
    peRatio: 22.8,
    dividendYield: 0,
    fiftyTwoHigh: 1210.94,
    fiftyTwoLow: 646.57,
    analystRating: "Buy",
    aiScore: 71,
    beta: 0.52,
    description: "Biotech powerhouse behind Dupixent, the fastest-growing drug in pharmaceutical history",
    thesis:
      "Dupixent is the fastest-growing drug in pharma history ($13B+ revenue) with expanding indications across 10+ allergic diseases. Deep internal pipeline including Linvoseltamab for myeloma and obesity program.",
    risks: [
      "Dupixent biosimilar entry in late 2020s reduces pricing power",
      "IRA Medicare drug price negotiation targeting Eylea revenue",
      "Pipeline diversification critical as Dupixent matures",
    ],
    catalysts: [
      "Dupixent new indications (COPD, CRSWNP) expanding patient population",
      "Linvoseltamab multiple myeloma approval in 2025",
      "Obesity and cardiometabolic pipeline early data",
    ],
  },
  {
    ticker: "DXCM",
    name: "DexCom Inc.",
    sector: "Healthcare",
    type: "stock" as const,
    price: 74.28,
    change: 0.84,
    changePercent: 1.14,
    marketCap: "$30B",
    peRatio: 48.2,
    dividendYield: 0,
    fiftyTwoHigh: 131.49,
    fiftyTwoLow: 64.03,
    analystRating: "Buy",
    aiScore: 69,
    beta: 1.38,
    description: "Continuous glucose monitoring leader for diabetics with 40M+ global patient opportunity",
    thesis:
      "CGM market leader with G7 sensor achieving best-in-class accuracy. Non-intensive diabetics represent 40M+ untapped patients now covered by Medicare. Stelo OTC CGM for prediabetes opens massive consumer market.",
    risks: [
      "Abbott FreeStyle Libre competing aggressively on price",
      "Execution stumble in 2024 hurt credibility with investors",
      "GLP-1 drugs reducing diabetes severity could limit CGM market growth",
    ],
    catalysts: [
      "Non-intensive diabetic CGM coverage driving Medicare volume",
      "Stelo OTC sensor targeting 100M+ prediabetic Americans",
      "Integration with insulin pump closed-loop systems",
    ],
  },
  // ─── Industrial (Freight / Equipment) ─────────────────────────────────
  {
    ticker: "ODFL",
    name: "Old Dominion Freight Line",
    sector: "Industrial",
    type: "stock" as const,
    price: 182.64,
    change: 1.28,
    changePercent: 0.71,
    marketCap: "$38B",
    peRatio: 28.4,
    dividendYield: 0.52,
    fiftyTwoHigh: 230.21,
    fiftyTwoLow: 163.08,
    analystRating: "Buy",
    aiScore: 72,
    beta: 0.98,
    description: "Best-in-class LTL freight carrier with industry-leading on-time delivery and damage rates",
    thesis:
      "Best-in-class LTL carrier with superior on-time delivery (99%+) and lowest damage rates in the industry. Pricing power from service quality. Yellow Freight bankruptcy created market share opportunity. Long-term capacity additions ahead of demand.",
    risks: [
      "Freight recession reducing shipment volumes",
      "Fuel cost volatility impacts operating ratio",
      "Yellow Freight volume gains not fully replacing lost industry capacity",
    ],
    catalysts: [
      "Yellow Freight market share consolidating to ODFL and other top carriers",
      "Industrial reshoring driving domestic freight volume growth",
      "Service center network expansion supporting long-haul volume",
    ],
  },
  {
    ticker: "URI",
    name: "United Rentals Inc.",
    sector: "Industrial",
    type: "stock" as const,
    price: 748.32,
    change: 6.84,
    changePercent: 0.92,
    marketCap: "$48B",
    peRatio: 16.8,
    dividendYield: 1.08,
    fiftyTwoHigh: 998.34,
    fiftyTwoLow: 632.72,
    analystRating: "Buy",
    aiScore: 74,
    beta: 1.42,
    description: "Largest equipment rental company in North America serving construction and industrial markets",
    thesis:
      "Largest equipment rental company in North America with scale advantages in purchasing, logistics, and customer coverage. CHIPS Act, IRA, and infrastructure bill driving multi-year construction super-cycle. Specialty rentals (climate control, power) growing faster than general fleet.",
    risks: [
      "Construction spending cyclicality tied to interest rates",
      "Fleet age and maintenance costs rising in downturn",
      "Sunbelt acquisition integration complexity",
    ],
    catalysts: [
      "Mega-project construction (chip fabs, LNG, data centers) requiring large rental fleets",
      "Specialty rentals expanding margin profile",
      "Used equipment sales supporting fleet value",
    ],
  },
  // ─── Real Estate (REITs) ───────────────────────────────────────────────
  {
    ticker: "PSA",
    name: "Public Storage",
    sector: "Real Estate",
    type: "stock" as const,
    price: 284.56,
    change: 1.44,
    changePercent: 0.51,
    marketCap: "$50B",
    peRatio: 28.8,
    dividendYield: 4.24,
    fiftyTwoHigh: 332.78,
    fiftyTwoLow: 248.94,
    analystRating: "Hold",
    aiScore: 60,
    beta: 0.62,
    description: "Largest self-storage REIT in the US with 3,000+ locations and national brand recognition",
    thesis:
      "Largest self-storage REIT with 3,000+ locations and national brand recognition driving premium occupancy. Self-storage demand driven by life events (moving, downsizing, divorce) making it recession-resilient. Digital-first leasing reducing labor costs.",
    risks: [
      "New supply in major markets pressuring street rates",
      "Rate hikes increasing borrowing costs for development",
      "Consumer spending slowdown reducing discretionary storage",
    ],
    catalysts: [
      "Revenue management technology optimizing street rate pricing",
      "European expansion via Shurgard ownership",
      "Acquisition opportunities as smaller operators face refinancing pressure",
    ],
  },
  {
    ticker: "EQIX",
    name: "Equinix Inc.",
    sector: "Real Estate",
    type: "stock" as const,
    price: 882.48,
    change: 7.28,
    changePercent: 0.83,
    marketCap: "$79B",
    peRatio: 82.4,
    dividendYield: 2.12,
    fiftyTwoHigh: 952.12,
    fiftyTwoLow: 728.54,
    analystRating: "Buy",
    aiScore: 79,
    beta: 0.88,
    description: "Global data center REIT with 260+ interconnection hubs in 33 countries",
    thesis:
      "Global data center REIT operating 260+ interconnection hubs across 33 countries. Network-neutral colocation enables enterprise hybrid cloud. AI workloads driving record data center demand. Interconnection business creates irreplaceable network effects.",
    risks: [
      "Power availability constraints limiting data center expansion",
      "Hyperscalers building own data centers could reduce colocation demand",
      "High capex and debt load from global expansion",
    ],
    catalysts: [
      "AI infrastructure demand driving record new bookings",
      "xScale joint ventures with GIC and CPPIB funding hyperscale builds",
      "Digital edge computing expansion in emerging markets",
    ],
  },
  // ─── Utilities ────────────────────────────────────────────────────────
  {
    ticker: "AEP",
    name: "American Electric Power",
    sector: "Utilities",
    type: "stock" as const,
    price: 98.84,
    change: 0.56,
    changePercent: 0.57,
    marketCap: "$53B",
    peRatio: 18.2,
    dividendYield: 3.68,
    fiftyTwoHigh: 107.44,
    fiftyTwoLow: 83.18,
    analystRating: "Hold",
    aiScore: 58,
    beta: 0.42,
    description: "Large regulated electric utility serving 5.6M customers across 11 states in the Midwest and South",
    thesis:
      "Large regulated utility serving 5.6M customers across 11 states. Transmission and distribution infrastructure investment driving rate base growth 7-9% annually. Data center and industrial load growth in service territory providing incremental demand.",
    risks: [
      "Rising interest rates increase cost of capital for regulated utilities",
      "Wildfire liability exposure growing in western service territories",
      "Regulatory lag between capex spend and rate recovery",
    ],
    catalysts: [
      "Data center and AI load additions in Ohio and Indiana service territory",
      "Transmission buildout receiving FERC-approved cost recovery",
      "Renewable generation investments growing regulated rate base",
    ],
  },
  // ─── Additional ──────────────────────────────────────────────────────
  {
    ticker: "LRCX",
    name: "Lam Research",
    sector: "Technology",
    type: "stock" as const,
    price: 78.42,
    change: 1.83,
    changePercent: 2.39,
    marketCap: "$102B",
    peRatio: 24.6,
    dividendYield: 1.12,
    fiftyTwoHigh: 113.00,
    fiftyTwoLow: 60.56,
    analystRating: "Buy",
    aiScore: 76,
    beta: 1.38,
    description: "Leading semiconductor equipment maker specializing in etch, deposition, and cleaning systems",
    thesis:
      "Critical semiconductor equipment supplier benefiting from CHIPS Act fab construction wave. Advanced etch technology essential for sub-3nm chip manufacturing. Installed base services providing recurring revenue stream.",
    risks: [
      "Semiconductor capex cyclicality creates revenue volatility",
      "China export restrictions limiting addressable market",
      "Customer concentration with TSMC and Samsung",
    ],
    catalysts: [
      "CHIPS Act driving $50B+ in new US fab construction",
      "Gate-all-around transistor architecture requiring more etch steps",
      "High-bandwidth memory demand for AI chips expanding tool intensity",
    ],
  },
  {
    ticker: "MNST",
    name: "Monster Beverage",
    sector: "Consumer",
    type: "stock" as const,
    price: 52.18,
    change: 0.34,
    changePercent: 0.66,
    marketCap: "$51B",
    peRatio: 32.8,
    dividendYield: 0,
    fiftyTwoHigh: 61.24,
    fiftyTwoLow: 44.27,
    analystRating: "Buy",
    aiScore: 69,
    beta: 0.92,
    description: "Leading energy drink maker with Monster, Reign, and Bang brands across 140+ countries",
    thesis:
      "Global energy drink category growing 8-10% annually with Monster as the clear #2 behind Red Bull. International expansion still early with significant whitespace in Asia and Africa. Coca-Cola distribution partnership provides unmatched global reach.",
    risks: [
      "Health concerns around energy drinks could drive regulatory action",
      "Input cost inflation in aluminum and sweeteners",
      "Intensifying competition from Celsius, Prime, and private label",
    ],
    catalysts: [
      "International revenue approaching 40% with room to grow",
      "Alcohol beverage segment (The Beast Unleashed) opening new category",
      "Price increases sticking with minimal volume elasticity",
    ],
  },
];
