"use client";

import { useState, useCallback } from "react";
import {
  Share2,
  Copy,
  Mail,
  Check,
  ExternalLink,
} from "lucide-react";
import { ARCHETYPE_INFO } from "@/lib/dna-scoring";
import type { BiasFlag, DNAProfile } from "@/lib/dna-scoring";
import type { StoredDNAProfile } from "@/lib/dna-storage";

// ---------------------------------------------------------------------------
// Shared profile type (subset sent via URL)
// ---------------------------------------------------------------------------

export interface SharedProfile {
  dimensions: DNAProfile["dimensions"];
  archetype: string;
  secondaryArchetype?: string;
  strengths: string[];
  vulnerabilities: string[];
  behavioralRule: string;
  biasFlags: BiasFlag[];
  marketMood: DNAProfile["marketMood"];
  confidence: { overall: number };
  completedAt: string;
}

// ---------------------------------------------------------------------------
// Encoding / decoding
// ---------------------------------------------------------------------------

export function encodeProfileForSharing(profile: StoredDNAProfile): string {
  const payload: SharedProfile = {
    dimensions: { ...profile.dimensions },
    archetype: profile.communicationArchetype,
    secondaryArchetype: profile.secondaryArchetype ?? undefined,
    strengths: [...profile.strengths],
    vulnerabilities: [...profile.vulnerabilities],
    behavioralRule: profile.behavioralRule,
    biasFlags: profile.biasFlags.map((b) => ({ ...b })),
    marketMood: { ...profile.marketMood },
    confidence: { overall: profile.confidence.overall },
    completedAt: profile.completedAt,
  };
  return btoa(encodeURIComponent(JSON.stringify(payload)));
}

export function decodeSharedProfile(hash: string): SharedProfile | null {
  try {
    const jsonStr = decodeURIComponent(atob(hash));
    return JSON.parse(jsonStr) as SharedProfile;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Text summary builder
// ---------------------------------------------------------------------------

function buildProfileSummary(
  profile: StoredDNAProfile | SharedProfile,
  archetype: string
): string {
  const dims = profile.dimensions;
  const lines = [
    "Investor Identity Assessment Results",
    "================================",
    "",
    `Investor Type: ${archetype}`,
    "",
    "Dimension Scores:",
    `  Risk Tolerance:  ${dims.R}/100`,
    `  Control Need:    ${dims.C}/100`,
    `  Time Horizon:    ${dims.H}/100`,
    `  Discipline:      ${dims.D}/100`,
    `  Emotional Reg:   ${dims.E}/100`,
    "",
    "Strengths:",
    ...profile.strengths.map((s) => `  + ${s}`),
    "",
    "Vulnerabilities:",
    ...profile.vulnerabilities.map((v) => `  ! ${v}`),
    "",
    `Behavioral Rule: ${profile.behavioralRule}`,
    "",
    "---",
    "Generated by StockPilot Investor Identity Assessment",
  ];
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// SharedBanner -- shown when viewing someone else's profile
// ---------------------------------------------------------------------------

export function SharedBanner() {
  return (
    <div className="bg-blue-bg border border-blue/20 rounded-xl p-4 mb-6 flex items-start gap-3">
      <ExternalLink className="w-4 h-4 text-blue flex-shrink-0 mt-0.5" />
      <div>
        <p className="text-sm font-semibold text-blue">Shared Assessment</p>
        <p className="text-xs text-text-secondary mt-0.5">
          This Investor Identity profile was shared with you for review. The data is
          read-only and comes directly from the investor&apos;s completed assessment.
        </p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// SharePanel modal
// ---------------------------------------------------------------------------

export function SharePanel({
  profile,
  onClose,
}: {
  profile: StoredDNAProfile;
  onClose: () => void;
}) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);

  const archetype = ARCHETYPE_INFO[profile.communicationArchetype as keyof typeof ARCHETYPE_INFO];
  const archetypeName = archetype?.name ?? profile.communicationArchetype;

  const shareUrl =
    typeof window !== "undefined"
      ? `${window.location.origin}/personality/results#shared=${encodeProfileForSharing(profile)}`
      : "";

  const summary = buildProfileSummary(profile, archetypeName);

  const emailSubject = encodeURIComponent(
    "My Investor Identity Assessment Results"
  );
  const emailBody = encodeURIComponent(
    `Hi,\n\nI completed a Investor Identity risk assessment and wanted to share my results with you.\n\nYou can view my full profile here:\n${shareUrl}\n\nOr see the summary below:\n\n${summary}`
  );
  const mailtoLink = `mailto:?subject=${emailSubject}&body=${emailBody}`;

  const handleCopyLink = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    } catch {
      // Fallback: clipboard API not available
    }
  }, [shareUrl]);

  const handleCopySummary = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopiedSummary(true);
      setTimeout(() => setCopiedSummary(false), 2000);
    } catch {
      // Fallback
    }
  }, [summary]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      <div className="relative bg-surface border border-border rounded-2xl w-full max-w-md overflow-hidden">
        <div className="p-5 border-b border-border">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-lg font-semibold">Share with Advisor</h2>
              <p className="text-xs text-text-muted mt-1">
                Send your Investor Identity results to your financial advisor
              </p>
            </div>
            <button
              onClick={onClose}
              className="text-text-muted hover:text-text-secondary transition-colors text-sm"
            >
              Close
            </button>
          </div>
        </div>

        <div className="p-5 space-y-4">
          {/* Shareable link */}
          <div>
            <label className="text-xs text-text-muted mb-1.5 block">
              Shareable Link
            </label>
            <div className="flex gap-2">
              <div className="flex-1 bg-surface-alt border border-border rounded-lg px-3 py-2 text-xs font-mono text-text-muted truncate">
                {shareUrl.slice(0, 60)}...
              </div>
              <button
                onClick={handleCopyLink}
                className={`px-3 py-2 rounded-lg text-xs font-medium flex items-center gap-1.5 transition-colors ${
                  copiedLink
                    ? "bg-green/10 text-green border border-green/30"
                    : "bg-surface-alt border border-border text-text-secondary hover:border-green/30"
                }`}
              >
                {copiedLink ? (
                  <>
                    <Check className="w-3.5 h-3.5" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    Copy
                  </>
                )}
              </button>
            </div>
            <p className="text-[10px] text-text-muted mt-1">
              Your advisor can view your full profile at this link -- no login
              required.
            </p>
          </div>

          {/* Copy summary */}
          <div>
            <label className="text-xs text-text-muted mb-1.5 block">
              Text Summary
            </label>
            <div className="bg-surface-alt border border-border rounded-lg p-3 text-[11px] text-text-secondary font-mono leading-relaxed max-h-32 overflow-y-auto whitespace-pre-wrap">
              {summary.slice(0, 300)}...
            </div>
            <button
              onClick={handleCopySummary}
              className={`mt-2 w-full px-3 py-2 rounded-lg text-xs font-medium flex items-center justify-center gap-1.5 transition-colors ${
                copiedSummary
                  ? "bg-green/10 text-green border border-green/30"
                  : "bg-surface-alt border border-border text-text-secondary hover:border-green/30"
              }`}
            >
              {copiedSummary ? (
                <>
                  <Check className="w-3.5 h-3.5" />
                  Copied to clipboard
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  Copy Full Summary
                </>
              )}
            </button>
          </div>

          {/* Email button */}
          <a
            href={mailtoLink}
            className="w-full px-4 py-2.5 rounded-lg text-black text-sm font-medium flex items-center justify-center gap-2 sp-btn-gradient"
          >
            <Mail className="w-4 h-4" />
            Email to Advisor
          </a>
        </div>
      </div>
    </div>
  );
}
